from rest_framework import routers

from .views import *

router = routers.DefaultRouter()
router.register(r"pegawai", PegawaiViewSet)
router.register(r"provinsi", SadProvinsiViewSet)
router.register(r"kabkota", SadKabKotaViewSet)
router.register(r"kecamatan", SadKecamatanViewSet)
router.register(r"desa", SadDesaViewSet)
router.register(r"batasdesa", BatasDesaViewSet)
router.register(r"saddusun", SadDusunViewSet)
router.register(r"saddukuh", SadDukuhViewSet)
router.register(r"sadrw", SadRwViewSet)
router.register(r"sadrt", SadRtViewSet)
router.register(r"keluarga", SadKeluargaViewSet)
router.register(r"penduduk", SadPendudukViewSet)
router.register(r"sarpras", SadSarprasViewSet)
router.register(r"inventaris", SadInventarisViewSet)
router.register(r"sigpemilik", SigPemilikViewSet)
router.register(r"sigbidang", SigBidangViewSet)
router.register(r"sigdesa", SigDesaViewSet)
router.register(r"sigdusun", SigDusunViewSet)
router.register(r"sigdukuh", SigDukuhViewSet)
router.register(r"sigrw", SigRwViewSet)
router.register(r"sigrt", SigRtViewSet)
router.register(r"kategorilapor", KategoriLaporViewSet)
router.register(r"kategoriinformasi", KategoriInformasiViewSet)
router.register(r"kategoriartikel", KategoriArtikelViewSet)
router.register(r"kategoripotensi", KategoriPotensiViewSet)
router.register(r"artikel", ArtikelViewSet)
router.register(r"informasi", InformasiViewSet)
# router.register(r"potensi", PotensiViewSet)
router.register(r"lapor", LaporViewSet)
router.register(r"slider", SliderViewSet)
router.register(r"kategoribelanja", KategoriBelanjaViewSet)
router.register(r"kategoripendapatan", KategoriPendapatanViewSet)
router.register(r"tahun", KategoriTahunViewSet)
router.register(r"anggaranbelanja", BelanjaViewSet)
router.register(r"anggaranpendapatan", PendapatanViewSet)
router.register(r"suratmasuk", SuratMasukViewSet)
router.register(r"suratkeluar", SuratKeluarViewSet)
router.register(r"statuslapor", StatusLaporViewSet)
router.register(r"suratkeluar", SuratKeluarViewSet)
router.register(r"pekerjaan", PekerjaanViewSet)
router.register(r"pendidikan", PendidikanViewSet)
router.register(r"agama", AgamaViewSet)
router.register(r"kelainanfisik", KelainanFisikViewSet)
router.register(r"cacat", CacatViewSet)
router.register(r"statusperkawinan", StatusPerkawinanViewSet)
router.register(r"kewarganegaraan", KewarganegaraanViewSet)
router.register(r"goldar", GoldarViewSet)
router.register(r"statusdlmkeluarga", StatusDlmKeluargaViewSet)
router.register(r"statuskesejahteraan", StatusKesejahteraanViewSet)
router.register(r"statuswarga", StatusWargaViewSet)
router.register(r"statusdatangmasuk", StatusDatangMasukViewSet)
router.register(r"asal", AsalViewSet)
router.register(r"keadaanawal", KeadaanAwalViewSet)
router.register(r"jabatan", JabatanViewSet)
router.register(r"statuspns", StatusPnsViewSet)
router.register(r"golongan", GolonganViewSet)
router.register(r"jeniskelahiran", JenisKelahiranViewSet)
router.register(r"jenistempat", JenisTempatViewSet)
router.register(r"tenagakesehatan", TenagaKesehatanViewSet)
router.register(r"absensi", AbsensiViewSet)
router.register(r"alasanizin", AlasanIzinViewSet)
router.register(r"laporanabsensi", LaporanAbsensiViewSet)
router.register(r"dashboard", DashboardViewSet, basename="Dashboard")
router.register(r"cctv", CctvViewSet)
router.register(r"sigkawasanhutan", SigKawasanHutanViewSet)
router.register(r"sigpenggunaantanah", SigPenggunaanTanahViewSet)
router.register(r"sigstatustanah", SigStatusTanahViewSet)
router.register(r"sigrtrw", SigArahanViewSet)
