# Generated by Django 2.2.17 on 2021-01-09 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0066_auto_20210109_0715'),
        ('layananperistiwa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SadPecahKK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadpecahkks', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadpecahkks', to=settings.AUTH_USER_MODEL)),
                ('keluarga', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadKeluarga')),
                ('penduduk', models.ManyToManyField(to='v1.SadPenduduk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadpecahkks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
