# Generated by Django 2.2.19 on 2021-03-29 08:17

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    AlasanPindah = apps.get_model("layananperistiwa", "AlasanPindah")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'layananperistiwa', 'migrations', 'csv', 'alasan_pindah.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        alasan_pindahs = []

        for row in reader:
            alasan_pindah = AlasanPindah(id=row[3],nama=row[4],label=row[5])
            
            alasan_pindahs.append(alasan_pindah)

        AlasanPindah.objects.bulk_create(alasan_pindahs)

def reverse_func(apps, schema_editor):
    AlasanPindah = apps.get_model("v1", "AlasanPindah")

    AlasanPindah.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('layananperistiwa', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
