# Generated by Django 2.2.19 on 2021-03-29 08:31

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    JenisPindah = apps.get_model("layananperistiwa", "JenisPindah")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'layananperistiwa', 'migrations', 'csv', 'jenis_pindah.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        jenis_pindahs = []

        for row in reader:
            jenis_pindah = JenisPindah(nama=row[4],label=row[5])
            
            jenis_pindahs.append(jenis_pindah)

        JenisPindah.objects.bulk_create(jenis_pindahs)

def reverse_func(apps, schema_editor):
    JenisPindah = apps.get_model("v1", "JenisPindah")

    JenisPindah.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('layananperistiwa', '0002_auto_20210329_1517'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
