# Generated by Django 2.2.17 on 2021-01-26 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layananperistiwa', '0002_sadpecahkk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratkelahiran',
            name='penolong_kelahiran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.TenagaKesehatan'),
        ),
        migrations.AlterField(
            model_name='suratkelahiran',
            name='tempat_dilahirkan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.JenisTempat'),
        ),
    ]
