# Generated by Django 2.2.17 on 2021-01-26 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layananperistiwa', '0003_auto_20210127_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratkelahiran',
            name='jenis_kelahiran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.JenisKelahiran'),
        ),
    ]
