# Generated by Django 2.2.19 on 2021-03-29 08:36

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    KlasifikasiPindah = apps.get_model("layananperistiwa", "KlasifikasiPindah")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'layananperistiwa', 'migrations', 'csv', 'klasifikasi_pindah.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        klasifikasi_pindahs = []

        for row in reader:
            klasifikasi_pindah = KlasifikasiPindah(nama=row[4],label=row[5])
            
            klasifikasi_pindahs.append(klasifikasi_pindah)

        KlasifikasiPindah.objects.bulk_create(klasifikasi_pindahs)

def reverse_func(apps, schema_editor):
    KlasifikasiPindah = apps.get_model("v1", "KlasifikasiPindah")

    KlasifikasiPindah.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('layananperistiwa', '0003_auto_20210329_1531'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
