# Generated by Django 2.2.19 on 2021-03-29 08:43

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    StatusKkPindah = apps.get_model("layananperistiwa", "StatusKkPindah")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'layananperistiwa', 'migrations', 'csv', 'status_kk_pindah.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        status_kk_pindahs = []

        for row in reader:
            status_kk_pindah = StatusKkPindah(nama=row[4],label=row[5])
            
            status_kk_pindahs.append(status_kk_pindah)

        StatusKkPindah.objects.bulk_create(status_kk_pindahs)

def reverse_func(apps, schema_editor):
    StatusKkPindah = apps.get_model("v1", "StatusKkPindah")

    StatusKkPindah.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('layananperistiwa', '0004_auto_20210329_1536'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
