# Generated by Django 2.2.17 on 2021-02-04 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layananperistiwa', '0005_sadlahirmati_nama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sadpindahmasuk',
            name='rt_id',
        ),
        migrations.AlterField(
            model_name='sadpindahmasuk',
            name='alamat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.Alamat'),
        ),
    ]
