# Generated by Django 2.2.19 on 2021-03-29 08:45

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    StatusKkTinggal = apps.get_model("layananperistiwa", "StatusKkTinggal")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'layananperistiwa', 'migrations', 'csv', 'status_kk_tinggal.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        status_kk_tinggals = []

        for row in reader:
            status_kk_tinggal = StatusKkTinggal(id=row[3],nama=row[4],label=row[5])
            
            status_kk_tinggals.append(status_kk_tinggal)

        StatusKkTinggal.objects.bulk_create(status_kk_tinggals)

def reverse_func(apps, schema_editor):
    StatusKkTinggal = apps.get_model("v1", "StatusKkTinggal")

    StatusKkTinggal.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('layananperistiwa', '0005_auto_20210329_1543'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
