# Generated by Django 2.2.17 on 2021-02-17 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0086_auto_20210217_1151'),
        ('layananperistiwa', '0006_auto_20210204_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='sadkelahiran',
            name='penduduk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadPenduduk'),
        ),
        migrations.AlterField(
            model_name='suratkelahiran',
            name='pegawai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.Pegawai'),
        ),
        migrations.AlterField(
            model_name='suratkelahiran',
            name='saksi1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='saksi1_surat_lahir', to='v1.SadPenduduk'),
        ),
        migrations.AlterField(
            model_name='suratkelahiran',
            name='saksi2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='saksi2_surat_lahir', to='v1.SadPenduduk'),
        ),
    ]
