# Generated by Django 2.2.17 on 2021-02-09 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0085_cctv'),
        ('layananperistiwa', '0006_auto_20210204_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='sadkelahiran',
            name='penduduk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadPenduduk'),
        ),
    ]
