# Generated by Django 2.2.17 on 2021-02-15 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layananperistiwa', '0007_sadkelahiran_penduduk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratkelahiran',
            name='pegawai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.Pegawai'),
        ),
        migrations.AlterField(
            model_name='suratkelahiran',
            name='saksi1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='saksi1_surat_lahir', to='v1.SadPenduduk'),
        ),
        migrations.AlterField(
            model_name='suratkelahiran',
            name='saksi2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='saksi2_surat_lahir', to='v1.SadPenduduk'),
        ),
    ]
