# Generated by Django 2.2.17 on 2021-02-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layananperistiwa', '0008_auto_20210211_1713'),
        ('layananperistiwa', '0008_auto_20210215_1009'),
    ]

    operations = [
    ]
