"""
Django settings for api_sad_sig project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
import environ
from pathlib import Path
from datetime import timedelta

env = environ.Env()
environ.Env.read_env()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
log_dir = os.path.join(os.path.dirname(BASE_DIR), "applog")
print(log_dir)

if not os.path.isdir(log_dir):
    os.mkdir(log_dir)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": log_dir + "/applog.log",
            "maxBytes": 2 * 1024 * 1024,
            "backupCount": "20",
        }
    },
    "root": {"handlers": ["file"], "level": "INFO"},
}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# This Desa
DESA_ID = env.str("DESA_ID")
# DESA_ID = 7505020008
# DESA_ID = 3515140008

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", [])
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:3000",
    "http://localhost:3000",
    "http://localhost:8000",
    "http://localhost:8080",
    "https://desajurangjero.istudios.id",
    "http://api-v2-n10-blanciran-desapintar.klatenkab.go.id",
    "https://api-v2-n10-blanciran-desapintar.klatenkab.go.id",
    "http://blanciran.karanganom.klatenkab.go.id",
    "https://blanciran.karanganom.klatenkab.go.id",
    "http://api-v2-n10-brangkal-desapintar.klatenkab.go.id",
    "https://api-v2-n10-brangkal-desapintar.klatenkab.go.id",
    "http://brangkal.karanganom.klatenkab.go.id",
    "https://brangkal.karanganom.klatenkab.go.id",
    "http://api-v2-n10-gempol-desapintar.klatenkab.go.id",
    "https://api-v2-n10-gempol-desapintar.klatenkab.go.id",
    "http://gempol.karanganom.klatenkab.go.id",
    "https://gempol.karanganom.klatenkab.go.id",
    "http://api-v2-n10-gledeg-desapintar.klatenkab.go.id",
    "https://api-v2-n10-gledeg-desapintar.klatenkab.go.id",
    "http://gledeg.karanganom.klatenkab.go.id",
    "https://gledeg.karanganom.klatenkab.go.id",
    "http://api-v2-n10-jambeyan-desapintar.klatenkab.go.id",
    "https://api-v2-n10-jambeyan-desapintar.klatenkab.go.id",
    "http://jambeyan.karanganom.klatenkab.go.id",
    "https://jambeyan.karanganom.klatenkab.go.id",
    "http://api-v2-n10-jeblok-desapintar.klatenkab.go.id",
    "https://api-v2-n10-jeblok-desapintar.klatenkab.go.id",
    "http://jeblok.karanganom.klatenkab.go.id",
    "https://jeblok.karanganom.klatenkab.go.id",
    "http://api-v2-n10-jungkare-desapintar.klatenkab.go.id",
    "https://api-v2-n10-jungkare-desapintar.klatenkab.go.id",
    "http://jungkare.karanganom.klatenkab.go.id",
    "https://jungkare.karanganom.klatenkab.go.id",
    "http://api-v2-n10-jurangjero-desapintar.klatenkab.go.id",
    "https://api-v2-n10-jurangjero-desapintar.klatenkab.go.id",
    "http://jurangjero.karanganom.klatenkab.go.id",
    "https://jurangjero.karanganom.klatenkab.go.id",
    "http://api-v2-n10-kadirejo-desapintar.klatenkab.go.id",
    "https://api-v2-n10-kadirejo-desapintar.klatenkab.go.id",
    "http://kadirejo.karanganom.klatenkab.go.id",
    "https://kadirejo.karanganom.klatenkab.go.id",
    "http://api-v2-n10-karangan-desapintar.klatenkab.go.id",
    "https://api-v2-n10-karangan-desapintar.klatenkab.go.id",
    "http://karangan.karanganom.klatenkab.go.id",
    "https://karangan.karanganom.klatenkab.go.id",
    "http://api-v2-n10-karanganom-desapintar.klatenkab.go.id",
    "https://api-v2-n10-karanganom-desapintar.klatenkab.go.id",
    "http://karanganom.karanganom.klatenkab.go.id",
    "https://karanganom.karanganom.klatenkab.go.id",
    "http://api-v2-n10-kunden-desapintar.klatenkab.go.id",
    "https://api-v2-n10-kunden-desapintar.klatenkab.go.id",
    "http://kunden.karanganom.klatenkab.go.id",
    "https://kunden.karanganom.klatenkab.go.id",
    "http://api-v2-n10-ngabeyan-desapintar.klatenkab.go.id",
    "https://api-v2-n10-ngabeyan-desapintar.klatenkab.go.id",
    "http://ngabeyan.karanganom.klatenkab.go.id",
    "https://ngabeyan.karanganom.klatenkab.go.id",
    "http://api-v2-n10-padas-desapintar.klatenkab.go.id",
    "https://api-v2-n10-padas-desapintar.klatenkab.go.id",
    "http://padas.karanganom.klatenkab.go.id",
    "https://padas.karanganom.klatenkab.go.id",
    "http://api-v2-n10-pondok-desapintar.klatenkab.go.id",
    "https://api-v2-n10-pondok-desapintar.klatenkab.go.id",
    "http://pondok.karanganom.klatenkab.go.id",
    "https://pondok.karanganom.klatenkab.go.id",
    "http://api-v2-n10-soropaten-desapintar.klatenkab.go.id",
    "https://api-v2-n10-soropaten-desapintar.klatenkab.go.id",
    "http://soropaten.karanganom.klatenkab.go.id",
    "https://soropaten.karanganom.klatenkab.go.id",
    "http://api-v2-n10-tarubasan-desapintar.klatenkab.go.id",
    "https://api-v2-n10-tarubasan-desapintar.klatenkab.go.id",
    "http://tarubasan.karanganom.klatenkab.go.id",
    "https://tarubasan.karanganom.klatenkab.go.id",
    "http://api-v2-n10-troso-desapintar.klatenkab.go.id",
    "https://api-v2-n10-troso-desapintar.klatenkab.go.id",
    "http://troso.karanganom.klatenkab.go.id",
    "https://troso.karanganom.klatenkab.go.id",
    "http://api-v2-n10-beku-desapintar.klatenkab.go.id",
    "https://api-v2-n10-beku-desapintar.klatenkab.go.id",
    "http://beku.karanganom.klatenkab.go.id",
    "https://beku.karanganom.klatenkab.go.id",
    "http://api-v2-n10-demo-desapintar.klatenkab.go.id",
    "https://api-v2-n10-demo-desapintar.klatenkab.go.id",
    "http://demo.karanganom.klatenkab.go.id",
    "https://demo.karanganom.klatenkab.go.id",
]
# CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    "v1.apps.V1Config",
    "users.apps.UsersConfig",
    "layananperistiwa.apps.LayananConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "dynamic_rest",
    "rest_framework",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "api_sad_sig.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "api_sad_sig.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {"default": env.db_url("DATABASE_URL")}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation." "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Jakarta"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_ROOT = "static/"
STATIC_URL = "/static/"

MEDIA_ROOT = env.str("MEDIA_ROOT")
MEDIA_URL = "/media/"


# CORS_ORIGIN_WHITELIST = [
#     "https://example.com",
#     "https://sub.example.com",
#     "http://localhost:3000",
#     "http://127.0.0.1:9000"
# ]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": (
        "rest_framework.pagination." "LimitOffsetPagination"
    ),
    "PAGE_SIZE": 50,
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
}
