from django.contrib import admin

# Register your models here.

from .models import *

admin.site.register(Pegawai)
admin.site.register(SadProvinsi)
admin.site.register(SadKabKota)
admin.site.register(SadKecamatan)
admin.site.register(SadDesa)
admin.site.register(SadDusunDukuh)
admin.site.register(SadRt)
admin.site.register(SadRw)
admin.site.register(SadKeluarga)
admin.site.register(SadPenduduk)
admin.site.register(SadKelahiran)
admin.site.register(SadKematian)
admin.site.register(SadLahirmati)
admin.site.register(SadPindahKeluar)
admin.site.register(SadPindahMasuk)
admin.site.register(SadSarpras)
admin.site.register(SadInventaris)
admin.site.register(SadSurat)
admin.site.register(SadDetailSurat)
admin.site.register(SigBidang)
admin.site.register(SigBidang2)
admin.site.register(SigDesa)
admin.site.register(SigDukuh)
admin.site.register(SigDusun)
admin.site.register(SigDukuh2)
admin.site.register(SigRw)
admin.site.register(SigRw2)
admin.site.register(SigRt)
admin.site.register(SigRt2)
admin.site.register(Slider)
admin.site.register(KategoriArtikel)
admin.site.register(Artikel)
admin.site.register(KategoriInformasi)
admin.site.register(Informasi)
admin.site.register(KategoriPotensi)
admin.site.register(Potensi)
admin.site.register(KategoriPotensi)
admin.site.register(Potensi)
admin.site.register(KategoriLapor)
admin.site.register(Lapor)