# Generated by Django 3.1.1 on 2020-10-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SadDesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_desa', models.CharField(blank=True, max_length=5, null=True)),
                ('nama_desa', models.CharField(blank=True, max_length=250, null=True)),
                ('alamat', models.CharField(blank=True, max_length=150, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=12, null=True)),
                ('kode_pos', models.CharField(blank=True, max_length=5, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('visi_misi', models.TextField(blank=True, null=True)),
                ('sejarah', models.TextField(blank=True, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sad_desa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SadDusunDukuh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desa_id', models.IntegerField(blank=True, null=True)),
                ('tipe', models.CharField(blank=True, max_length=5, null=True)),
                ('nama', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'sad_dusun_dukuh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SadKabKota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kab_kota', models.CharField(blank=True, max_length=5, null=True)),
                ('nama_kab_kota', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sad_kab_kota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SadKecamatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kecamatan', models.CharField(blank=True, max_length=5, null=True)),
                ('nama_kecamatan', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'sad_kecamatan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SadKeluarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kk', models.CharField(blank=True, max_length=16, null=True)),
                ('alamat', models.CharField(blank=True, max_length=100, null=True)),
                ('kode_pos', models.CharField(blank=True, max_length=5, null=True)),
                ('status_kesejahteraan', models.CharField(blank=True, max_length=30, null=True)),
                ('penghasil', models.IntegerField(blank=True, null=True)),
                ('status_kk', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sad_keluarga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SadPenduduk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(blank=True, max_length=16, null=True)),
                ('chip_ektp', models.CharField(blank=True, max_length=10, null=True)),
                ('nama', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('jk', models.CharField(blank=True, max_length=10, null=True)),
                ('agama', models.CharField(blank=True, max_length=20, null=True)),
                ('pendidikan', models.CharField(blank=True, max_length=20, null=True)),
                ('pekerjaan', models.CharField(blank=True, max_length=50, null=True)),
                ('status_kawin', models.CharField(blank=True, max_length=20, null=True)),
                ('status_penduduk', models.CharField(blank=True, max_length=20, null=True)),
                ('kewarganegaraan', models.CharField(blank=True, max_length=5, null=True)),
                ('anak_ke', models.CharField(blank=True, max_length=5, null=True)),
                ('golongan_darah', models.CharField(blank=True, max_length=5, null=True)),
                ('status_dalam_keluarga', models.CharField(blank=True, max_length=20, null=True)),
                ('no_paspor', models.CharField(blank=True, max_length=20, null=True)),
                ('suku', models.CharField(blank=True, max_length=20, null=True)),
                ('potensi_diri', models.CharField(blank=True, max_length=50, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=13, null=True)),
                ('nik_ayah', models.CharField(blank=True, max_length=18, null=True)),
                ('nik_ibu', models.CharField(blank=True, max_length=18, null=True)),
                ('nama_ayah', models.CharField(blank=True, max_length=45, null=True)),
                ('nama_ibu', models.CharField(blank=True, max_length=45, null=True)),
                ('tgl_exp_paspor', models.DateField(blank=True, null=True)),
                ('akta_lahir', models.CharField(blank=True, max_length=18, null=True)),
                ('akta_kawin', models.CharField(blank=True, max_length=18, null=True)),
                ('tgl_kawin', models.DateField(blank=True, null=True)),
                ('akta_cerai', models.CharField(blank=True, max_length=18, null=True)),
                ('tgl_cerai', models.DateField(blank=True, null=True)),
                ('kelainan_fisik', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.BinaryField(blank=True, null=True)),
                ('pass_field', models.CharField(blank=True, db_column='pass', max_length=20, null=True)),
            ],
            options={
                'db_table': 'sad_penduduk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SadProvinsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_provinsi', models.CharField(blank=True, max_length=5, null=True)),
                ('nama_provinsi', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sad_provinsi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SadRt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'sad_rt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SadRw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desa_id', models.IntegerField(blank=True, null=True)),
                ('rw', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'sad_rw',
                'managed': False,
            },
        ),
    ]
