# Generated by Django 2.2.17 on 2020-11-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_auto_20201130_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sigrt',
            old_name='rw',
            new_name='sig_rw',
        ),
    ]
