# Generated by Django 2.2.17 on 2020-12-01 08:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_auto_20201130_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigBidang2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sig_bidang2',
            },
        ),
        migrations.CreateModel(
            name='SigDukuh2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dukuh', models.CharField(blank=True, max_length=70, null=True)),
                ('luas', models.CharField(blank=True, max_length=10, null=True)),
                ('keliling', models.CharField(blank=True, max_length=10, null=True)),
                ('geometry', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('sig_desa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigDesa')),
            ],
            options={
                'db_table': 'sig_dukuh2',
            },
        ),
        migrations.CreateModel(
            name='SigRt2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt', models.CharField(blank=True, max_length=10, null=True)),
                ('geometry', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sig_rt2',
            },
        ),
        migrations.CreateModel(
            name='SigRw2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rw', models.CharField(blank=True, max_length=10, null=True)),
                ('geometry', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('sig_dukuh2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigDukuh2')),
            ],
            options={
                'db_table': 'sig_rw2',
            },
        ),
        migrations.RemoveField(
            model_name='sigsaddusundukuh',
            name='sad_dusun_dukuh',
        ),
        migrations.RemoveField(
            model_name='sigsaddusundukuh',
            name='sig_dusun_dukuh',
        ),
        migrations.RemoveField(
            model_name='sigsadrt',
            name='sad_rt',
        ),
        migrations.RemoveField(
            model_name='sigsadrt',
            name='sig_rt',
        ),
        migrations.RemoveField(
            model_name='sigsadrw',
            name='sad_rw',
        ),
        migrations.RemoveField(
            model_name='sigsadrw',
            name='sig_rw',
        ),
        migrations.RemoveField(
            model_name='sigbidang',
            name='desa',
        ),
        migrations.AddField(
            model_name='sigbidang',
            name='sig_dukuh2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigDukuh'),
        ),
        migrations.AddField(
            model_name='sigrt',
            name='geometry',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sigrw',
            name='geometry',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SigDusunDukuh',
        ),
        migrations.DeleteModel(
            name='SigSadDusunDukuh',
        ),
        migrations.DeleteModel(
            name='SigSadRt',
        ),
        migrations.DeleteModel(
            name='SigSadRw',
        ),
        migrations.AddField(
            model_name='sigrt2',
            name='sig_rw2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigRw2'),
        ),
        migrations.AddField(
            model_name='sigbidang2',
            name='sig_dukuh2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigDukuh2'),
        ),
    ]
