# Generated by Django 2.2.17 on 2020-12-07 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0011_auto_20201203_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriArtikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'KategoriArtikel',
            },
        ),
        migrations.CreateModel(
            name='KategoriInformasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'KategoriInformasi',
            },
        ),
        migrations.CreateModel(
            name='KategoriPotensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'KategoriPotensi',
            },
        ),
        migrations.AlterField(
            model_name='slider',
            name='gambar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Potensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, max_length=100, null=True)),
                ('isi', models.TextField(blank=True, null=True)),
                ('geometry', models.TextField(blank=True, null=True)),
                ('gambar', models.TextField(blank=True, null=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.KategoriPotensi')),
            ],
            options={
                'db_table': 'Potensi',
            },
        ),
        migrations.CreateModel(
            name='Informasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, max_length=100, null=True)),
                ('tempat', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('mulai', models.CharField(blank=True, max_length=10, null=True)),
                ('selesai', models.CharField(blank=True, max_length=10, null=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.KategoriInformasi')),
            ],
            options={
                'db_table': 'Informasi',
            },
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, max_length=100, null=True)),
                ('isi', models.TextField(blank=True, null=True)),
                ('gambar', models.TextField(blank=True, null=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.KategoriArtikel')),
            ],
            options={
                'db_table': 'Artikel',
            },
        ),
    ]
