# Generated by Django 2.2.17 on 2020-12-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_auto_20201207_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='potensi',
            name='bidang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='potensi',
            name='centroid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='potensi',
            name='harga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
