# Generated by Django 2.2.17 on 2020-12-07 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0013_auto_20201207_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriLapor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'KategoriLapor',
            },
        ),
        migrations.CreateModel(
            name='Lapor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, max_length=100, null=True)),
                ('isi', models.TextField(blank=True, null=True)),
                ('gambar', models.TextField(blank=True, null=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.KategoriLapor')),
            ],
            options={
                'db_table': 'Lapor',
            },
        ),
    ]
