# Generated by Django 2.2.17 on 2020-12-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0013_auto_20201206_0822'),
        ('v1', '0014_kategorilapor_lapor'),
    ]

    operations = [
    ]
