# Generated by Django 2.2.17 on 2021-02-18 01:51

import api_sad_sig.util
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'agama',
            },
        ),
        migrations.CreateModel(
            name='Alamat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('jalan_blok', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_alamats', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_alamats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alamat',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlasanIzin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'alasan_izin',
            },
        ),
        migrations.CreateModel(
            name='Asal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'asal',
            },
        ),
        migrations.CreateModel(
            name='Cacat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cacat',
            },
        ),
        migrations.CreateModel(
            name='Cctv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('koordinat', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cctv',
            },
        ),
        migrations.CreateModel(
            name='Goldar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'goldar',
            },
        ),
        migrations.CreateModel(
            name='Golongan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'golongan',
            },
        ),
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'jabatan',
            },
        ),
        migrations.CreateModel(
            name='JenisKelahiran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'jenis_kelahiran',
            },
        ),
        migrations.CreateModel(
            name='JenisTempat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'jenis_tempat',
            },
        ),
        migrations.CreateModel(
            name='KategoriArtikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'KategoriArtikel',
            },
        ),
        migrations.CreateModel(
            name='KategoriBelanja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, max_length=10, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('jumlah_anggaran', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kategori_belanja',
            },
        ),
        migrations.CreateModel(
            name='KategoriInformasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'KategoriInformasi',
            },
        ),
        migrations.CreateModel(
            name='KategoriLapor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
            ],
            options={
                'db_table': 'KategoriLapor',
            },
        ),
        migrations.CreateModel(
            name='KategoriPendapatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, max_length=10, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('jumlah_anggaran', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kategori_pendapatan',
            },
        ),
        migrations.CreateModel(
            name='KategoriPotensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'KategoriPotensi',
            },
        ),
        migrations.CreateModel(
            name='KategoriTahun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'kategori_tahun',
            },
        ),
        migrations.CreateModel(
            name='KeadaanAwal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'keadaan_awal',
            },
        ),
        migrations.CreateModel(
            name='KelainanFisik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'kelainanfisik',
            },
        ),
        migrations.CreateModel(
            name='KepemilikanNonWarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namabidang', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'kepemilikan_non_warga',
            },
        ),
        migrations.CreateModel(
            name='KepemilikanWarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namabidang', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'kepemilikan',
            },
        ),
        migrations.CreateModel(
            name='Kewarganegaraan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'kewarganegaraan',
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nip', models.CharField(blank=True, max_length=18, null=True)),
                ('chip_ektp', models.CharField(blank=True, max_length=20, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('jabatan', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('golongan', models.CharField(blank=True, max_length=30, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_pegawais', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_pegawais', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_pegawais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pegawai',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pekerjaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pekerjaan',
            },
        ),
        migrations.CreateModel(
            name='PemilikNonWarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(blank=True, max_length=32, null=True)),
                ('nama', models.CharField(max_length=64)),
                ('namabidang', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'pemilik_non_warga',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pendidikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pendidikan',
            },
        ),
        migrations.CreateModel(
            name='SadDesa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kode_desa', models.CharField(blank=True, max_length=25, null=True)),
                ('nama_desa', models.CharField(blank=True, max_length=250, null=True)),
                ('alamat', models.CharField(blank=True, max_length=150, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=12, null=True)),
                ('kode_pos', models.CharField(blank=True, max_length=5, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('visi_misi', models.TextField(blank=True, null=True)),
                ('sejarah', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_saddesas', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_saddesas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sad_desa',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SadDusun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nama', models.CharField(blank=True, max_length=70, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_saddusuns', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_saddusuns', to=settings.AUTH_USER_MODEL)),
                ('desa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadDesa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_saddusuns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sad_dusun',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SadKabKota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kode_kab_kota', models.CharField(blank=True, max_length=5, null=True)),
                ('nama_kab_kota', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadkabkotas', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadkabkotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sad_kab_kota',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SadKeluarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('no_kk', models.CharField(max_length=16, unique=True)),
                ('jalan_blok', models.CharField(blank=True, max_length=100, null=True)),
                ('kode_pos', models.CharField(blank=True, max_length=5, null=True)),
                ('status_kesejahteraan', models.CharField(blank=True, max_length=30, null=True)),
                ('penghasilan', models.IntegerField(blank=True, null=True)),
                ('status_kk', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.Alamat')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadkeluargas', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadkeluargas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sad_keluarga',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SadPenduduk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('chip_ektp', models.CharField(blank=True, max_length=10, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('jk', models.CharField(blank=True, max_length=12, null=True)),
                ('alamat', models.CharField(blank=True, max_length=200, null=True)),
                ('agama', models.CharField(blank=True, max_length=20, null=True)),
                ('pendidikan', models.CharField(blank=True, max_length=100, null=True)),
                ('pekerjaan', models.CharField(blank=True, max_length=100, null=True)),
                ('status_kawin', models.CharField(blank=True, max_length=20, null=True)),
                ('status_penduduk', models.CharField(blank=True, max_length=20, null=True)),
                ('kewarganegaraan', models.CharField(blank=True, max_length=20, null=True)),
                ('anak_ke', models.CharField(blank=True, max_length=5, null=True)),
                ('golongan_darah', models.CharField(blank=True, max_length=5, null=True)),
                ('status_dalam_keluarga', models.CharField(blank=True, max_length=20, null=True)),
                ('no_paspor', models.CharField(blank=True, max_length=20, null=True)),
                ('suku', models.CharField(blank=True, max_length=20, null=True)),
                ('potensi_diri', models.CharField(blank=True, max_length=50, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=13)),
                ('nik_ayah', models.CharField(blank=True, max_length=18, null=True)),
                ('nik_ibu', models.CharField(blank=True, max_length=18, null=True)),
                ('nama_ayah', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_ibu', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_exp_paspor', models.DateField(blank=True, null=True)),
                ('akta_lahir', models.CharField(blank=True, max_length=18, null=True)),
                ('akta_kawin', models.CharField(blank=True, max_length=18, null=True)),
                ('tgl_kawin', models.DateField(blank=True, null=True)),
                ('akta_cerai', models.CharField(blank=True, max_length=18, null=True)),
                ('tgl_cerai', models.DateField(blank=True, null=True)),
                ('kelainan_fisik', models.CharField(blank=True, max_length=100, null=True)),
                ('cacat', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
                ('pass_field', models.CharField(blank=True, db_column='pass', max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadpenduduks', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadpenduduks', to=settings.AUTH_USER_MODEL)),
                ('keluarga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='anggota', to='v1.SadKeluarga', to_field='no_kk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadpenduduks', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sad_penduduk',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SigBidang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nbt', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('latitude', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('gambar_atas', models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
                ('gambar_depan', models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
                ('penguasa_nonwarga', django.contrib.postgres.fields.jsonb.JSONField(blank=True, max_length=64, null=True)),
                ('geometry', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigbidangs', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigbidangs', to=settings.AUTH_USER_MODEL)),
                ('pemiliknonwarga', models.ManyToManyField(through='v1.KepemilikanNonWarga', to='v1.PemilikNonWarga')),
                ('pemilikwarga', models.ManyToManyField(through='v1.KepemilikanWarga', to='v1.SadPenduduk')),
            ],
            options={
                'db_table': 'sig_bidang',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SigDesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nama_desa', models.CharField(blank=True, max_length=250, null=True)),
                ('luas', models.CharField(blank=True, max_length=10, null=True)),
                ('keliling', models.CharField(blank=True, max_length=10, null=True)),
                ('geometry', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigdesas', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigdesas', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigdesas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sig_desa',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SigDukuh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nama_dukuh', models.CharField(blank=True, max_length=70, null=True)),
                ('luas', models.CharField(blank=True, max_length=10, null=True)),
                ('keliling', models.CharField(blank=True, max_length=10, null=True)),
                ('geometry', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigdukuhs', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigdukuhs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sig_dukuh',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SigDusun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nama_dusun', models.CharField(blank=True, max_length=70, null=True)),
                ('luas', models.CharField(blank=True, max_length=10, null=True)),
                ('keliling', models.CharField(blank=True, max_length=10, null=True)),
                ('geometry', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigdusuns', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigdusuns', to=settings.AUTH_USER_MODEL)),
                ('sig_desa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigDesa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigdusuns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sig_dusun',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusDatangMasuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'status_datang_masuk',
            },
        ),
        migrations.CreateModel(
            name='StatusDlmKeluarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'status_dalam_keluarga',
            },
        ),
        migrations.CreateModel(
            name='StatusKesejahteraan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'status_kesejahteraan',
            },
        ),
        migrations.CreateModel(
            name='StatusLapor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('warna', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'StatusLapor',
            },
        ),
        migrations.CreateModel(
            name='StatusPerkawinan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'status_perkawinan',
            },
        ),
        migrations.CreateModel(
            name='StatusPns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'status_pns',
            },
        ),
        migrations.CreateModel(
            name='StatusWarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'status_warga',
            },
        ),
        migrations.CreateModel(
            name='SuratKeluar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_surat', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_kirim', models.DateField(blank=True, null=True)),
                ('tgl_surat', models.DateField(blank=True, null=True)),
                ('pengirim', models.CharField(blank=True, max_length=100, null=True)),
                ('kepada', models.CharField(blank=True, max_length=100, null=True)),
                ('perihal', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('arsip_suratkeluar', models.FileField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
            ],
            options={
                'db_table': 'surat_keluar',
            },
        ),
        migrations.CreateModel(
            name='SuratMasuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_surat', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_terima', models.DateField(blank=True, null=True)),
                ('tgl_surat', models.DateField(blank=True, null=True)),
                ('pengirim', models.CharField(blank=True, max_length=100, null=True)),
                ('kepada', models.CharField(blank=True, max_length=100, null=True)),
                ('perihal', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('arsip_suratmasuk', models.FileField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
            ],
            options={
                'db_table': 'surat_masuk',
            },
        ),
        migrations.CreateModel(
            name='TenagaKesehatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tenaga_kesehatan',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('judul', models.CharField(blank=True, max_length=100, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sliders', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sliders', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sliders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slider',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SigSadDesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigsaddesas', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigsaddesas', to=settings.AUTH_USER_MODEL)),
                ('sad_desa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadDesa')),
                ('sig_desa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigDesa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigsaddesas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sig_sad_desa',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SigSadBidang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pemilik', models.CharField(blank=True, max_length=100, null=True)),
                ('penguasa', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigsadbidangs', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigsadbidangs', to=settings.AUTH_USER_MODEL)),
                ('sad_penduduk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadPenduduk')),
                ('sig_bidang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigBidang')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigsadbidangs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sig_sad_bidang',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SigRw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rw', models.CharField(blank=True, max_length=10, null=True)),
                ('geometry', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigrws', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigrws', to=settings.AUTH_USER_MODEL)),
                ('sig_dukuh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigDukuh')),
                ('sig_dusun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigDusun')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigrws', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sig_rw',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SigRt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rt', models.CharField(blank=True, max_length=10, null=True)),
                ('geometry', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigrts', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigrts', to=settings.AUTH_USER_MODEL)),
                ('sig_rw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigRw')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigrts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sig_rt',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SigPemilik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('penguasa', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigpemiliks', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigpemiliks', to=settings.AUTH_USER_MODEL)),
                ('pemilik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadPenduduk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigpemiliks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sig_pemilik',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SigDukuh2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nama_dukuh', models.CharField(blank=True, max_length=70, null=True)),
                ('luas', models.CharField(blank=True, max_length=10, null=True)),
                ('keliling', models.CharField(blank=True, max_length=10, null=True)),
                ('geometry', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigdukuh2s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigdukuh2s', to=settings.AUTH_USER_MODEL)),
                ('sig_desa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigDesa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigdukuh2s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sig_dukuh2',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sigdukuh',
            name='sig_dusun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigDusun'),
        ),
        migrations.AddField(
            model_name='sigdukuh',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigdukuhs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigbidang',
            name='sig_dusun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigDusun'),
        ),
        migrations.AddField(
            model_name='sigbidang',
            name='sig_rt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigRt'),
        ),
        migrations.AddField(
            model_name='sigbidang',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigbidangs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SettingDesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=20, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_settingdesas', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_settingdesas', to=settings.AUTH_USER_MODEL)),
                ('desa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadDesa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_settingdesas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'setting_desa',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SadSurat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('judul', models.CharField(blank=True, max_length=100, null=True)),
                ('sifat', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadsurats', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadsurats', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadsurats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sad_surat',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SadSarpras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nama_sarpras', models.CharField(blank=True, max_length=100, null=True)),
                ('asal', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_awal', models.DateField(blank=True, null=True)),
                ('keadaan_awal', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_hapus', models.DateField(blank=True, null=True)),
                ('ket_hapus', models.CharField(blank=True, max_length=50, null=True)),
                ('keadaan_akhir', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tahun', models.CharField(blank=True, max_length=4, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadsarprass', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadsarprass', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadsarprass', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sad_sarpras',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SadRw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rw', models.CharField(blank=True, max_length=10, null=True)),
                ('namarw', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadrws', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadrws', to=settings.AUTH_USER_MODEL)),
                ('dusun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadDusun')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadrws', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sad_rw',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SadRt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rt', models.CharField(blank=True, max_length=10, null=True)),
                ('namart', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadrts', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadrts', to=settings.AUTH_USER_MODEL)),
                ('rw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadRw')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadrts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sad_rt',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SadProvinsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kode_provinsi', models.CharField(blank=True, max_length=5, null=True)),
                ('nama_provinsi', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadprovinsis', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadprovinsis', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadprovinsis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sad_provinsi',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sadkeluarga',
            name='menguasai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dikuasai', to='v1.SigBidang'),
        ),
        migrations.AddField(
            model_name='sadkeluarga',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadkeluargas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SadKecamatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kode_kecamatan', models.CharField(blank=True, max_length=5, null=True)),
                ('nama_kecamatan', models.CharField(blank=True, max_length=250, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadkecamatans', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadkecamatans', to=settings.AUTH_USER_MODEL)),
                ('kab_kota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadKabKota')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadkecamatans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sad_kecamatan',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sadkabkota',
            name='provinsi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadProvinsi'),
        ),
        migrations.AddField(
            model_name='sadkabkota',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadkabkotas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SadInventaris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nama_inventaris', models.CharField(blank=True, max_length=100, null=True)),
                ('asal', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_awal', models.DateField(blank=True, null=True)),
                ('keadaan_awal', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_hapus', models.DateField(blank=True, null=True)),
                ('ket_hapus', models.CharField(blank=True, max_length=50, null=True)),
                ('keadaan_akhir', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tahun', models.CharField(blank=True, max_length=4, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadinventariss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadinventariss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadinventariss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sad_inventaris',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SadDetailSurat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('no_surat', models.CharField(blank=True, max_length=50, null=True)),
                ('lampiran', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=50, null=True)),
                ('tempat_tujuan', models.CharField(blank=True, max_length=50, null=True)),
                ('pengikut_pindah', models.CharField(blank=True, max_length=50, null=True)),
                ('asal', models.CharField(blank=True, max_length=50, null=True)),
                ('barang_yg_hilang', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_jam_kehilangan', models.CharField(blank=True, max_length=50, null=True)),
                ('pelapor', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_yg_sama', models.CharField(blank=True, max_length=50, null=True)),
                ('keperluan', models.CharField(blank=True, max_length=50, null=True)),
                ('berlaku_mulai', models.DateField(blank=True, null=True)),
                ('sampai_dengan', models.DateField(blank=True, null=True)),
                ('nama_acara', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_acara', models.DateField(blank=True, null=True)),
                ('tempat_acara', models.CharField(blank=True, max_length=50, null=True)),
                ('jenis_hiburan', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_grup', models.CharField(blank=True, max_length=50, null=True)),
                ('pimpinan_acara', models.CharField(blank=True, max_length=50, null=True)),
                ('jumlah_keluarga_yg_pindah', models.CharField(blank=True, max_length=50, null=True)),
                ('hubungan', models.CharField(blank=True, max_length=50, null=True)),
                ('data_penduduk_luar_desa', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_saddetailsurats', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_saddetailsurats', to=settings.AUTH_USER_MODEL)),
                ('pegawai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.Pegawai')),
                ('surat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadSurat')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_saddetailsurats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sad_detail_surat',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='saddesa',
            name='kecamatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadKecamatan'),
        ),
        migrations.AddField(
            model_name='saddesa',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_saddesas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Potensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_usaha', models.CharField(blank=True, max_length=100, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=100, null=True)),
                ('judul', models.CharField(blank=True, max_length=100, null=True)),
                ('isi', models.TextField(blank=True, null=True)),
                ('koordinat', models.TextField(blank=True, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.KategoriPotensi')),
            ],
            options={
                'db_table': 'Potensi',
            },
        ),
        migrations.CreateModel(
            name='Pendapatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, max_length=20, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('anggaran', models.CharField(blank=True, max_length=100, null=True)),
                ('sumber_dana', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl', models.DateField(blank=True, null=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.KategoriPendapatan')),
                ('tahun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.KategoriTahun')),
            ],
            options={
                'db_table': 'pendapatan',
            },
        ),
        migrations.CreateModel(
            name='Lapor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('judul', models.CharField(blank=True, max_length=100, null=True)),
                ('isi', models.TextField(blank=True, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_lapors', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_lapors', to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.KategoriLapor')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.StatusLapor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_lapors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Lapor',
            },
        ),
        migrations.AddField(
            model_name='kepemilikanwarga',
            name='bidang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigBidang'),
        ),
        migrations.AddField(
            model_name='kepemilikanwarga',
            name='penduduk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadPenduduk'),
        ),
        migrations.AddField(
            model_name='kepemilikannonwarga',
            name='bidang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigBidang'),
        ),
        migrations.AddField(
            model_name='kepemilikannonwarga',
            name='non_penduduk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.PemilikNonWarga'),
        ),
        migrations.CreateModel(
            name='Informasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, max_length=100, null=True)),
                ('tempat', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('mulai', models.CharField(blank=True, max_length=10, null=True)),
                ('selesai', models.CharField(blank=True, max_length=10, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.KategoriInformasi')),
            ],
            options={
                'db_table': 'Informasi',
            },
        ),
        migrations.CreateModel(
            name='Belanja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, max_length=20, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('anggaran', models.CharField(blank=True, max_length=100, null=True)),
                ('sumber_dana', models.CharField(blank=True, max_length=100, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('tgl', models.DateField(blank=True, null=True)),
                ('foto_sebelum', models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
                ('foto_sesudah', models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
                ('progres', models.CharField(blank=True, max_length=100, null=True)),
                ('koordinat', models.TextField(blank=True, null=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.KategoriBelanja')),
                ('tahun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.KategoriTahun')),
            ],
            options={
                'db_table': 'belanja',
            },
        ),
        migrations.CreateModel(
            name='BatasDesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('utara', models.CharField(blank=True, max_length=50, null=True)),
                ('selatan', models.CharField(blank=True, max_length=50, null=True)),
                ('timur', models.CharField(blank=True, max_length=50, null=True)),
                ('barat', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_batasdesas', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_batasdesas', to=settings.AUTH_USER_MODEL)),
                ('desa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadDesa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_batasdesas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'batas_desa',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl', models.DateField(blank=True, null=True)),
                ('judul', models.CharField(blank=True, max_length=100, null=True)),
                ('isi', models.TextField(blank=True, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.KategoriArtikel')),
            ],
            options={
                'db_table': 'Artikel',
            },
        ),
        migrations.AddField(
            model_name='alamat',
            name='desa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_alamat', to='v1.SadDesa'),
        ),
        migrations.AddField(
            model_name='alamat',
            name='dusun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadDusun'),
        ),
        migrations.AddField(
            model_name='alamat',
            name='rt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadRt'),
        ),
        migrations.AddField(
            model_name='alamat',
            name='rw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadRw'),
        ),
        migrations.AddField(
            model_name='alamat',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_alamats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_masuk', models.DateTimeField(blank=True, null=True)),
                ('jam_keluar', models.DateTimeField(blank=True, null=True)),
                ('alasan_izin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.AlasanIzin')),
                ('pegawai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='absensi', to='v1.Pegawai')),
            ],
            options={
                'db_table': 'absensi',
            },
        ),
    ]
