# Generated by Django 2.2.23 on 2021-07-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nasabah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'nasabah',
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.CharField(max_length=200)),
                ('debit_credit_status', models.CharField(max_length=5)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'transaksi',
            },
        ),
    ]
