# Generated by Django 2.2.17 on 2021-02-24 03:48

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0002_auto_20210222_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigArahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('luas', models.CharField(blank=True, max_length=100, null=True)),
                ('arahan', models.CharField(blank=True, max_length=100, null=True)),
                ('pola_ruang', models.CharField(blank=True, max_length=100, null=True)),
                ('fungsi', models.CharField(blank=True, max_length=100, null=True)),
                ('geometry', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigarahans', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigarahans', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigarahans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sig_arahan',
                'abstract': False,
            },
        ),
    ]
