# Generated by Django 2.2.23 on 2021-07-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_transaksi_nasabah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='transaction_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
