# Generated by Django 2.2.16 on 2020-11-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_sigdusundukuh_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigdusundukuh',
            name='keliling',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sigdusundukuh',
            name='luas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
