# Generated by Django 2.2.17 on 2021-02-22 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0002_auto_20210222_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigPenggunaanWarna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('warna', models.CharField(blank=True, max_length=100, null=True)),
                ('penggunaan', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigpenggunaanwarnas', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigpenggunaanwarnas', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigpenggunaanwarnas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sig_penggunaan_warna',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='sigpenggunaantanah',
            name='penggunaan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigPenggunaanWarna'),
        ),
    ]
