# Generated by Django 2.2.17 on 2020-11-14 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0003_auto_20201107_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='sadkeluarga',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sadkeluarga',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='keluarga_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadkeluarga',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sadkeluarga',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_column='deleted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='keluarga_delete_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadkeluarga',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sadkeluarga',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='keluarga_update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
