# Generated by Django 2.2.17 on 2021-02-24 04:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_auto_20210224_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctv',
            name='koordinat',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
