# Generated by Django 2.2.17 on 2020-11-29 07:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_auto_20201114_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigDusun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dusun', models.CharField(blank=True, max_length=70, null=True)),
                ('luas', models.CharField(blank=True, max_length=10, null=True)),
                ('keliling', models.CharField(blank=True, max_length=10, null=True)),
                ('geometry', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('sig_desa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigDesa')),
            ],
            options={
                'db_table': 'sig_dusun',
            },
        ),
        migrations.CreateModel(
            name='SigDukuh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dukuh', models.CharField(blank=True, max_length=70, null=True)),
                ('luas', models.CharField(blank=True, max_length=10, null=True)),
                ('keliling', models.CharField(blank=True, max_length=10, null=True)),
                ('geometry', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('sig_dusun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigDusun')),
            ],
            options={
                'db_table': 'sig_dukuh',
            },
        ),
    ]
