# Generated by Django 2.2.17 on 2021-02-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_auto_20210224_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigbidang',
            name='luas',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sigbidang',
            name='pemanfaatan_tanah',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sigbidang',
            name='penggunaan_tanah',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sigbidang',
            name='rtrw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sigbidang',
            name='status_hak',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
