# Generated by Django 2.2.17 on 2020-11-30 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_sigdukuh_sigdusun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sigrw',
            name='dusun_dukuh',
        ),
        migrations.AddField(
            model_name='sigrw',
            name='dukuh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigDukuh'),
        ),
    ]
