# Generated by Django 2.2.19 on 2021-02-25 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_auto_20210225_1348'),
        ('v1', '0003_auto_20210222_1724'),
    ]

    operations = [
    ]
