# Generated by Django 2.2.17 on 2020-11-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_auto_20201130_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sigrw',
            old_name='dukuh',
            new_name='sig_dukuh',
        ),
        migrations.RemoveField(
            model_name='sigrw',
            name='desa',
        ),
    ]
