# Generated by Django 2.2.19 on 2021-02-25 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_auto_20210226_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='alamat',
            name='dukuh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadDukuh'),
        ),
    ]
