# Generated by Django 2.2.19 on 2021-02-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_alamat_dukuh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Potensi',
        ),
    ]
