# Generated by Django 2.2.19 on 2021-03-26 03:05
from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    Pendidikan = apps.get_model("v1", "Pendidikan")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'pendidikan.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        pendidikans = []

        for row in reader:
            pendidikan = Pendidikan(nama=row[1])
            
            pendidikans.append(pendidikan)

        Pendidikan.objects.bulk_create(pendidikans)

def reverse_func(apps, schema_editor):
    Pendidikan = apps.get_model("v1", "Pendidikan")

    Pendidikan.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_potensi'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
