# Generated by Django 2.2.19 on 2021-03-26 06:17

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    Pekerjaan = apps.get_model("v1", "Pekerjaan")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'pekerjaan.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        pekerjaans = []

        for row in reader:
            pekerjaan = Pekerjaan(nama=row[1])
            
            pekerjaans.append(pekerjaan)

        Pekerjaan.objects.bulk_create(pekerjaans)

def reverse_func(apps, schema_editor):
    Pekerjaan = apps.get_model("v1", "Pekerjaan")

    Pekerjaan.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0011_auto_20210326_1005'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
