# Generated by Django 2.2.19 on 2021-03-26 06:29

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    Agama = apps.get_model("v1", "Agama")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'agama.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        agamas = []

        for row in reader:
            agama = Agama(nama=row[1])
            
            agamas.append(agama)

        Agama.objects.bulk_create(agamas)

def reverse_func(apps, schema_editor):
    Agama = apps.get_model("v1", "Agama")

    Agama.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_auto_20210326_1317'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
