# Generated by Django 2.2.17 on 2020-12-06 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0012_auto_20201206_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_pegawais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_pegawais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_pegawais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saddesa',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_saddesas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saddesa',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_saddesas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saddesa',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_saddesas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saddetailsurat',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_saddetailsurats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saddetailsurat',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_saddetailsurats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saddetailsurat',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_saddetailsurats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saddusundukuh',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_saddusundukuhs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saddusundukuh',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_saddusundukuhs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saddusundukuh',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_saddusundukuhs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadinventaris',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadinventariss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadinventaris',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadinventariss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadinventaris',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadinventariss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadkabkota',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadkabkotas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadkabkota',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadkabkotas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadkabkota',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadkabkotas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadkecamatan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadkecamatans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadkecamatan',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadkecamatans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadkecamatan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadkecamatans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadkelahiran',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadkelahirans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadkelahiran',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadkelahirans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadkelahiran',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadkelahirans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadkematian',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadkematians', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadkematian',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadkematians', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadkematian',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadkematians', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadlahirmati',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadlahirmatis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadlahirmati',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadlahirmatis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadlahirmati',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadlahirmatis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadpenduduk',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadpenduduks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadpenduduk',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadpenduduks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadpenduduk',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadpenduduks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadpindahkeluar',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadpindahkeluars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadpindahkeluar',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadpindahkeluars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadpindahkeluar',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadpindahkeluars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadpindahmasuk',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadpindahmasuks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadpindahmasuk',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadpindahmasuks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadpindahmasuk',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadpindahmasuks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadprovinsi',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadprovinsis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadprovinsi',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadprovinsis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadprovinsi',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadprovinsis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadrt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadrts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadrt',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadrts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadrt',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadrts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadrw',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadrws', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadrw',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadrws', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadrw',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadrws', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadsarpras',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadsarprass', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadsarpras',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadsarprass', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadsarpras',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadsarprass', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadsurat',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadsurats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadsurat',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadsurats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sadsurat',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadsurats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settingdesa',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_settingdesas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settingdesa',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_settingdesas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settingdesa',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_settingdesas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigbidang',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigbidangs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigbidang',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigbidangs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigbidang',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigbidangs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigbidang2',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigbidang2s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigbidang2',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigbidang2s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigbidang2',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigbidang2s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigdesa',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigdesas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigdesa',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigdesas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigdesa',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigdesas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigdukuh',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigdukuhs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigdukuh',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigdukuhs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigdukuh',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigdukuhs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigdukuh2',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigdukuh2s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigdukuh2',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigdukuh2s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigdukuh2',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigdukuh2s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigdusun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigdusuns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigdusun',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigdusuns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigdusun',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigdusuns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigrt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigrts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigrt',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigrts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigrt',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigrts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigrt2',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigrt2s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigrt2',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigrt2s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigrt2',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigrt2s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigrw',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigrws', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigrw',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigrws', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigrw',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigrws', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigrw2',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigrw2s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigrw2',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigrw2s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigrw2',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigrw2s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigsadbidang',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigsadbidangs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigsadbidang',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigsadbidangs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigsadbidang',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigsadbidangs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigsadbidang2',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigsadbidang2s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigsadbidang2',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigsadbidang2s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigsadbidang2',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigsadbidang2s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigsaddesa',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigsaddesas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigsaddesa',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigsaddesas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sigsaddesa',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigsaddesas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slider',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sliders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slider',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sliders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slider',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sliders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sadkeluarga',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadkeluargas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sadkeluarga',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadkeluargas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sadkeluarga',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadkeluargas', to=settings.AUTH_USER_MODEL),
        ),
    ]
