# Generated by Django 2.2.19 on 2021-03-26 06:41

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    Asal = apps.get_model("v1", "Asal")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'asal.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        asals = []

        for row in reader:
            asal = Asal(nama=row[1])
            
            asals.append(asal)

        Asal.objects.bulk_create(asals)

def reverse_func(apps, schema_editor):
    Asal = apps.get_model("v1", "Asal")

    Asal.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0013_auto_20210326_1329'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
