# Generated by Django 2.2.19 on 2021-03-26 06:48

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    BatasDesa = apps.get_model("v1", "BatasDesa")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'batas_desa.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        batas_desas = []

        for row in reader:
            batas_desa = BatasDesa(utara=row[4],selatan=row[5],timur=row[6],barat=row[7])
            
            batas_desas.append(batas_desa)

        BatasDesa.objects.bulk_create(batas_desas)

def reverse_func(apps, schema_editor):
    BatasDesa = apps.get_model("v1", "BatasDesa")

    BatasDesa.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0014_auto_20210326_1341'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
