# Generated by Django 2.2.19 on 2021-03-26 06:53

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    Cacat = apps.get_model("v1", "Cacat")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'cacat.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        cacats = []

        for row in reader:
            cacat = Cacat(nama=row[1])
            
            cacats.append(cacat)

        Cacat.objects.bulk_create(cacats)

def reverse_func(apps, schema_editor):
    Cacat = apps.get_model("v1", "Cacat")

    Cacat.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0015_auto_20210326_1348'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
