# Generated by Django 2.2.17 on 2020-12-08 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0015_merge_20201207_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadkeluarga',
            name='no_kk',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='sadpenduduk',
            name='keluarga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='anggota', to='v1.SadKeluarga', to_field='no_kk'),
        ),
        migrations.AlterField(
            model_name='sadpenduduk',
            name='nik',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
