# Generated by Django 2.2.19 on 2021-03-26 06:56

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    Goldar = apps.get_model("v1", "Goldar")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'goldar.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        goldars = []

        for row in reader:
            goldar = Goldar(nama=row[1])
            
            goldars.append(goldar)

        Goldar.objects.bulk_create(goldars)

def reverse_func(apps, schema_editor):
    Goldar = apps.get_model("v1", "Goldar")

    Goldar.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0016_auto_20210326_1353'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
