# Generated by Django 2.2.17 on 2020-12-09 13:36

import v1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0016_auto_20201208_0122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artikel",
            name="gambar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=v1.models.file_destination,
            ),
        ),
    ]
