# Generated by Django 2.2.17 on 2020-12-09 14:11

from django.db import migrations, models
import v1.models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0017_auto_20201209_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapor',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=v1.models.file_destination),
        ),
        migrations.AlterField(
            model_name='potensi',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=v1.models.file_destination),
        ),
        migrations.AlterField(
            model_name='slider',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=v1.models.file_destination),
        ),
    ]
