# Generated by Django 2.2.19 on 2021-03-26 07:00

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    Jabatan = apps.get_model("v1", "Jabatan")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'jabatan.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        jabatans = []

        for row in reader:
            jabatan = Jabatan(nama=row[1])
            
            jabatans.append(jabatan)

        Jabatan.objects.bulk_create(jabatans)

def reverse_func(apps, schema_editor):
    Jabatan = apps.get_model("v1", "Jabatan")

    Jabatan.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0018_auto_20210326_1358'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
