# Generated by Django 2.2.17 on 2020-12-13 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0020_auto_20201213_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratSkck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_surat', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('keperluan', models.TextField(blank=True, null=True)),
                ('pegawai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.Pegawai')),
                ('penduduk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadPenduduk')),
            ],
        ),
        migrations.CreateModel(
            name='SuratKelahiran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('no_surat', models.CharField(blank=True, max_length=50, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('jk', models.CharField(blank=True, max_length=15, null=True)),
                ('tempat_dilahirkan', models.CharField(blank=True, max_length=50, null=True)),
                ('tempat_kelahiran', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl', models.DateField(blank=True, null=True)),
                ('jenis_kelahiran', models.CharField(blank=True, max_length=15, null=True)),
                ('kelahiran_ke', models.CharField(blank=True, max_length=15, null=True)),
                ('penolong_kelahiran', models.CharField(blank=True, max_length=15, null=True)),
                ('berat', models.CharField(blank=True, max_length=15, null=True)),
                ('panjang', models.CharField(blank=True, max_length=15, null=True)),
                ('ayah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ayah_surat_lahir', to='v1.SadPenduduk')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_suratkelahirans', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_suratkelahirans', to=settings.AUTH_USER_MODEL)),
                ('ibu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ibu_surat_lahir', to='v1.SadPenduduk')),
                ('pegawai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.Pegawai')),
                ('saksi1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='saksi1_surat_lahir', to='v1.SadPenduduk')),
                ('saksi2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='saksi2_surat_lahir', to='v1.SadPenduduk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_suratkelahirans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuratDomisili',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_surat', models.CharField(blank=True, max_length=50, null=True)),
                ('keperluan', models.TextField(blank=True, null=True)),
                ('pegawai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.Pegawai')),
                ('penduduk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadPenduduk')),
            ],
        ),
    ]
