# Generated by Django 2.2.17 on 2020-12-14 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0021_suratdomisili_suratkelahiran_suratskck'),
    ]

    operations = [
        migrations.AddField(
            model_name='sadpenduduk',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suratkelahiran',
            name='pegawai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='acc_surat_kelahiran', to='v1.Pegawai'),
        ),
    ]
