# Generated by Django 2.2.19 on 2021-03-26 07:07

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    KategoriTahun = apps.get_model("v1", "KategoriTahun")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'kategori_tahun.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        kategori_tahuns = []

        for row in reader:
            kategori_tahun = KategoriTahun(nama=row[1])
            
            kategori_tahuns.append(kategori_tahun)

        KategoriTahun.objects.bulk_create(kategori_tahuns)

def reverse_func(apps, schema_editor):
    KategoriTahun = apps.get_model("v1", "KategoriTahun")

    KategoriTahun.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0021_auto_20210326_1405'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
