# Generated by Django 2.2.17 on 2020-12-14 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0022_auto_20201214_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadpenduduk',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
