# Generated by Django 2.2.17 on 2020-12-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0021_auto_20201214_1212'),
        ('v1', '0023_auto_20201214_0341'),
    ]

    operations = [
    ]
