# Generated by Django 2.2.19 on 2021-03-26 07:14

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    KategoriLapor = apps.get_model("v1", "KategoriLapor")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'KategoriLapor.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        kategori_lapors = []

        for row in reader:
            kategori_lapor = KategoriLapor(nama=row[1])
            
            kategori_lapors.append(kategori_lapor)

        KategoriLapor.objects.bulk_create(kategori_lapors)

def reverse_func(apps, schema_editor):
    KategoriLapor = apps.get_model("v1", "KategoriLapor")

    KategoriLapor.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0024_auto_20210326_1411'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
