# Generated by Django 2.2.19 on 2021-03-26 07:16

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    KategoriPotensi = apps.get_model("v1", "KategoriPotensi")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'KategoriPotensi.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        kategori_potensis = []

        for row in reader:
            kategori_potensi = KategoriPotensi(nama=row[1])
            
            kategori_potensis.append(kategori_potensi)

        KategoriPotensi.objects.bulk_create(kategori_potensis)

def reverse_func(apps, schema_editor):
    KategoriPotensi = apps.get_model("v1", "KategoriPotensi")

    KategoriPotensi.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0025_auto_20210326_1414'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
