# Generated by Django 2.2.17 on 2020-12-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0025_auto_20201214_0628'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='suratdomisili',
            table='surat_domisili',
        ),
        migrations.AlterModelTable(
            name='suratkelahiran',
            table='surat_kelahiran',
        ),
        migrations.AlterModelTable(
            name='suratskck',
            table='surat_skck',
        ),
    ]
