# Generated by Django 2.2.17 on 2020-12-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0026_auto_20201214_0742'),
        ('v1', '0024_merge_20201214_0903'),
    ]

    operations = [
    ]
