# Generated by Django 2.2.17 on 2020-12-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0027_merge_20201214_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saddesa',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
