# Generated by Django 2.2.17 on 2020-12-16 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import v1.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0028_auto_20201216_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sigbidang',
            old_name='pemilik',
            new_name='pemilik_nonwarga',
        ),
        migrations.AlterField(
            model_name='sadinventaris',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=v1.models.file_destination),
        ),
        migrations.AlterField(
            model_name='sadsarpras',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=v1.models.file_destination),
        ),
        migrations.CreateModel(
            name='SigPemilik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('penguasa', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigpemiliks', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigpemiliks', to=settings.AUTH_USER_MODEL)),
                ('pemilik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadPenduduk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigpemiliks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sig_pemilik',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sigbidang',
            name='pemilik_warga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigPemilik'),
        ),
    ]
