# Generated by Django 2.2.19 on 2021-03-26 07:27

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    Kewarganegaraan = apps.get_model("v1", "Kewarganegaraan")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'kewarganegaraan.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        kewarganegaraans = []

        for row in reader:
            kewarganegaraan = Kewarganegaraan(nama=row[1])
            
            kewarganegaraans.append(kewarganegaraan)

        Kewarganegaraan.objects.bulk_create(kewarganegaraans)

def reverse_func(apps, schema_editor):
    Kewarganegaraan = apps.get_model("v1", "Kewarganegaraan")

    Kewarganegaraan.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0028_auto_20210326_1423'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
