# Generated by Django 2.2.17 on 2020-12-17 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import v1.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0029_auto_20201216_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPindah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nama', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_jenispindahs', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_jenispindahs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_jenispindahs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jenis_pindah',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sadpindahkeluar',
            name='kecamatan_tujuan',
        ),
        migrations.RemoveField(
            model_name='sadpindahkeluar',
            name='klarifikasi_pindah',
        ),
        migrations.RemoveField(
            model_name='sadpindahkeluar',
            name='kota_tujuan',
        ),
        migrations.RemoveField(
            model_name='sadpindahkeluar',
            name='provinsi_tujuan',
        ),
        migrations.RemoveField(
            model_name='sadpindahkeluar',
            name='status_no_kk_pindah',
        ),
        migrations.AlterField(
            model_name='saddesa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=v1.models.file_destination),
        ),
        migrations.AlterField(
            model_name='sadpindahkeluar',
            name='jenis_kepindahan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_keluar_jenis', to='v1.JenisPindah'),
        ),
        migrations.AlterField(
            model_name='sadpindahkeluar',
            name='keluarga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_keluar', to='v1.SadKeluarga'),
        ),
        migrations.AlterField(
            model_name='sadpindahkeluar',
            name='pemohon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_keluar', to='v1.SadPenduduk'),
        ),
        migrations.CreateModel(
            name='StatusKKTinggal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('nama', models.CharField(default='label', max_length=64)),
                ('label', models.CharField(default='nama', max_length=128)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_statuskktinggals', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_statuskktinggals', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_statuskktinggals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'status_kk_tinggal',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusKKPindah',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('nama', models.CharField(default='label', max_length=64)),
                ('label', models.CharField(default='nama', max_length=128)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_statuskkpindahs', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_statuskkpindahs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_statuskkpindahs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'status_kk_pindah',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KlasifikasiPindah',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('nama', models.CharField(default='label', max_length=64)),
                ('label', models.CharField(default='nama', max_length=128)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_klasifikasipindahs', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_klasifikasipindahs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_klasifikasipindahs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'klasifikasi_pindah',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlasanPindah',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('nama', models.CharField(default='label', max_length=64)),
                ('label', models.CharField(default='nama', max_length=128)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_alasanpindahs', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_alasanpindahs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_alasanpindahs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alasan_pindah',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sadpindahkeluar',
            name='klasifikasi_pindah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_keluar_klasifikasi', to='v1.KlasifikasiPindah'),
        ),
        migrations.AddField(
            model_name='sadpindahkeluar',
            name='status_kk_pindah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_keluar_kk_pindah', to='v1.StatusKKPindah'),
        ),
        migrations.AddField(
            model_name='sadpindahkeluar',
            name='status_kk_tinggal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_keluar_kk_tinggal', to='v1.StatusKKTinggal'),
        ),
    ]
