# Generated by Django 2.2.19 on 2021-03-26 07:31

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    StatusKesejahteraan = apps.get_model("v1", "StatusKesejahteraan")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'status_kesejahteraan.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        status_kesejahteraans = []

        for row in reader:
            status_kesejahteraan = StatusKesejahteraan(nama=row[1])
            
            status_kesejahteraans.append(status_kesejahteraan)

        StatusKesejahteraan.objects.bulk_create(status_kesejahteraans)

def reverse_func(apps, schema_editor):
    StatusKesejahteraan = apps.get_model("v1", "StatusKesejahteraan")

    StatusKesejahteraan.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0030_auto_20210326_1429'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
