# Generated by Django 2.2.17 on 2020-12-17 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0031_pegawai_gambar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatasDesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('utara', models.CharField(blank=True, max_length=50, null=True)),
                ('selatan', models.CharField(blank=True, max_length=50, null=True)),
                ('timur', models.CharField(blank=True, max_length=50, null=True)),
                ('barat', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_batasdesas', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_batasdesas', to=settings.AUTH_USER_MODEL)),
                ('desa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadDesa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_batasdesas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'batas_desa',
                'abstract': False,
            },
        ),
    ]
