# Generated by Django 2.2.19 on 2021-03-26 07:34

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    StatusPns = apps.get_model("v1", "StatusPns")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'status_pns.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        status_pnss = []

        for row in reader:
            status_pns = StatusPns(nama=row[1])
            
            status_pnss.append(status_pns)

        StatusPns.objects.bulk_create(status_pnss)

def reverse_func(apps, schema_editor):
    StatusPns = apps.get_model("v1", "StatusPns")

    StatusPns.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0032_auto_20210326_1433'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
