# Generated by Django 2.2.17 on 2020-12-17 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0032_batasdesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadpindahkeluar',
            name='alasan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_keluar_alasan', to='v1.AlasanPindah'),
        ),
    ]
