# Generated by Django 2.2.17 on 2020-12-17 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0033_auto_20201217_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadpindahkeluar',
            name='kelurahan_tujuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadDesa'),
        ),
    ]
