# Generated by Django 2.2.19 on 2021-03-26 07:35

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    StatusWarga = apps.get_model("v1", "StatusWarga")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'status_warga.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        status_wargas = []

        for row in reader:
            status_warga = StatusWarga(nama=row[1])
            
            status_wargas.append(status_warga)

        StatusWarga.objects.bulk_create(status_wargas)

def reverse_func(apps, schema_editor):
    StatusWarga = apps.get_model("v1", "StatusWarga")

    StatusWarga.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0033_auto_20210326_1434'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
