# Generated by Django 2.2.19 on 2021-03-26 07:36

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    TenagaKesehatan = apps.get_model("v1", "TenagaKesehatan")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'tenaga_kesehatan.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        tenaga_kesehatans = []

        for row in reader:
            tenaga_kesehatan = TenagaKesehatan(nama=row[1])
            
            tenaga_kesehatans.append(tenaga_kesehatan)

        TenagaKesehatan.objects.bulk_create(tenaga_kesehatans)

def reverse_func(apps, schema_editor):
    TenagaKesehatan = apps.get_model("v1", "TenagaKesehatan")

    TenagaKesehatan.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0034_auto_20210326_1435'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
