# Generated by Django 2.2.17 on 2020-12-18 01:40

from django.db import migrations, models
import v1.models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0034_auto_20201217_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='informasi',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=v1.models.file_destination),
        ),
    ]
