# Generated by Django 2.2.19 on 2021-03-29 03:21

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    SadProvinsi = apps.get_model("v1", "SadProvinsi")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'provinsi.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        sad_provinsis = []

        for row in reader:
            sad_provinsi = SadProvinsi(id=row[0],nama_provinsi=row[5])
            
            sad_provinsis.append(sad_provinsi)

        SadProvinsi.objects.bulk_create(sad_provinsis)

def reverse_func(apps, schema_editor):
    SadProvinsi = apps.get_model("v1", "SadProvinsi")

    SadProvinsi.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0035_auto_20210326_1436'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
