# Generated by Django 2.2.17 on 2020-12-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0035_informasi_gambar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sadpindahkeluar',
            name='keluarga',
        ),
        migrations.RemoveField(
            model_name='sadpindahkeluar',
            name='pemohon',
        ),
        migrations.AddField(
            model_name='sadpindahkeluar',
            name='nik_pemohon',
            field=models.CharField(default='', max_length=54),
        ),
        migrations.AddField(
            model_name='sadpindahkeluar',
            name='nik_pindah',
            field=models.CharField(default='', max_length=72),
        ),
        migrations.AddField(
            model_name='sadpindahkeluar',
            name='nomor_kk',
            field=models.CharField(default='', max_length=54),
        ),
    ]
