# Generated by Django 2.2.17 on 2020-12-19 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0036_auto_20201218_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sadpindahmasuk',
            name='status_no_kk_pindah',
        ),
        migrations.RemoveField(
            model_name='sadpindahmasuk',
            name='yang_datang',
        ),
        migrations.AddField(
            model_name='sadpindahmasuk',
            name='nik_datang',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='sadpindahmasuk',
            name='status_kk_pindah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.StatusKKPindah'),
        ),
        migrations.AlterField(
            model_name='sadpindahmasuk',
            name='rt_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadRt'),
        ),
    ]
