# Generated by Django 2.2.19 on 2021-03-29 03:24

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    SadKabKota = apps.get_model("v1", "SadKabKota")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'sad_kab_kota.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        sad_kab_kotas = []

        for row in reader:
            sad_kab_kota = SadKabKota(id=row[0],nama_kab_kota=row[5],provinsi_id=row[8])
            
            sad_kab_kotas.append(sad_kab_kota)

        SadKabKota.objects.bulk_create(sad_kab_kotas)

def reverse_func(apps, schema_editor):
    SadKabKota = apps.get_model("v1", "SadKabKota")

    SadKabKota.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0036_auto_20210329_1021'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
