# Generated by Django 2.2.19 on 2021-03-29 03:25

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    SadKecamatan = apps.get_model("v1", "SadKecamatan")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'sad_kecamatan.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        sad_kecamatans = []

        for row in reader:
            
            sad_kecamatan = SadKecamatan(id=row[0],nama_kecamatan=row[5],kab_kota_id=row[8])
            
            sad_kecamatans.append(sad_kecamatan)

        SadKecamatan.objects.bulk_create(sad_kecamatans)

def reverse_func(apps, schema_editor):
    SadKecamatan = apps.get_model("v1", "SadKecamatan")

    SadKecamatan.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0037_auto_20210329_1024'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
