# Generated by Django 2.2.17 on 2020-12-20 03:02

from django.db import migrations, models
import v1.models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0037_auto_20201219_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorilapor',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=v1.models.file_destination),
        ),
    ]
