# Generated by Django 2.2.19 on 2021-03-29 07:40

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    StatusLapor = apps.get_model("v1", "StatusLapor")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'StatusLapor.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        statuslapors = []

        for row in reader:
            statuslapor = StatusLapor(nama=row[1],warna=row[2])
            
            statuslapors.append(statuslapor)

        StatusLapor.objects.bulk_create(statuslapors)

def reverse_func(apps, schema_editor):
    StatusLapor = apps.get_model("v1", "StatusLapor")

    StatusLapor.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0038_auto_20210329_1025'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
