# Generated by Django 2.2.17 on 2020-12-20 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0038_kategorilapor_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigbidang',
            name='namabidang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sigbidang',
            name='pemilik_warga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadPenduduk'),
        ),
    ]
