# Generated by Django 2.2.19 on 2021-04-01 08:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0038_auto_20210329_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapor',
            name='is_approvement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='potensi',
            name='is_approvement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saddesa',
            name='center',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
