# Generated by Django 2.2.19 on 2021-03-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0039_auto_20210329_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='saddesa',
            name='center',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
