# Generated by Django 2.2.17 on 2020-12-20 22:59

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0040_auto_20201220_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sigbidang',
            name='pemilik_nonwarga',
        ),
        migrations.AlterField(
            model_name='sadkeluarga',
            name='menguasai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dikuasai', to='v1.SigBidang'),
        ),
        migrations.AlterField(
            model_name='sigbidang',
            name='pemilik_warga',
            field=models.ManyToManyField(to='v1.SadPenduduk'),
        ),
        migrations.AlterField(
            model_name='sigbidang',
            name='penguasa_nonwarga',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='PemilikNonWarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nik', models.CharField(max_length=32, unique=True)),
                ('nama', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_pemiliknonwargas', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_pemiliknonwargas', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_pemiliknonwargas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sigbidang',
            name='pemilik_non_warga',
            field=models.ManyToManyField(to='v1.PemilikNonWarga'),
        ),
    ]
