# Generated by Django 2.2.19 on 2021-04-03 12:50

from __future__ import unicode_literals

from django.db import migrations
import csv, os
from pathlib import Path

def load_initial_data(apps, schema_editor):
    Slider = apps.get_model("v1", "Slider")

    BASE_DIR = Path(__file__).resolve().parent.parent
    with open(os.path.join(os.path.dirname(BASE_DIR), 'v1', 'migrations', 'csv', 'slider.csv')) as csv_file:
        reader = csv.reader(csv_file)
        # header = next(reader)

        sliders = []

        for row in reader:
            slider = Slider(judul=row[4],deskripsi=row[5],gambar=row[6])
            
            sliders.append(slider)

        Slider.objects.bulk_create(sliders)

def reverse_func(apps, schema_editor):
    Slider = apps.get_model("v1", "Slider")

    Slider.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0040_auto_20210403_1944'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
