# Generated by Django 2.2.19 on 2021-03-29 10:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0042_auto_20210329_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saddesa',
            name='center',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
