# Generated by Django 2.2.19 on 2021-04-08 03:59

import api_sad_sig.util
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0042_auto_20210403_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiayaKunjungan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peserta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('narasumber', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'biaya_kunjungan',
            },
        ),
        migrations.AlterField(
            model_name='absensi',
            name='jam_keluar',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='jam_masuk',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Kunjungan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('pic', models.CharField(blank=True, max_length=100, null=True)),
                ('selaku_apa', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_eo', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl', models.DateField(blank=True, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=100, null=True)),
                ('surat', models.FileField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
                ('jumlah', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('pemateri1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pemateri1', to='v1.Pegawai')),
                ('pemateri2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pemateri2', to='v1.Pegawai')),
            ],
            options={
                'db_table': 'kunjungan',
            },
        ),
    ]
