# Generated by Django 2.2.19 on 2021-03-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0043_auto_20210329_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapor',
            name='is_approvement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='potensi',
            name='is_approvement',
            field=models.BooleanField(default=False),
        ),
    ]
