# Generated by Django 2.2.17 on 2020-12-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0043_auto_20201222_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potensi',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='potensi',
            name='jenis_promosi',
        ),
    ]
