# Generated by Django 2.2.19 on 2021-04-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0044_sigpotensi'),
    ]

    operations = [
        migrations.AddField(
            model_name='saddesa',
            name='zoom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
