# Generated by Django 2.2.17 on 2020-12-22 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0044_auto_20201222_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriBelanja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, max_length=10, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('jumlah_anggaran', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kategori_belanja',
            },
        ),
        migrations.CreateModel(
            name='KategoriPendapatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, max_length=10, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('jumlah_anggaran', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kategori_pendapatan',
            },
        ),
        migrations.CreateModel(
            name='KategoriTahun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'kategori_tahun',
            },
        ),
        migrations.CreateModel(
            name='Pendapatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, max_length=20, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('anggaran', models.CharField(blank=True, max_length=100, null=True)),
                ('sumber_dana', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl', models.DateField(blank=True, null=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.KategoriPendapatan')),
                ('tahun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.KategoriTahun')),
            ],
            options={
                'db_table': 'pendapatan',
            },
        ),
        migrations.CreateModel(
            name='Belanja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, max_length=20, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('anggaran', models.CharField(blank=True, max_length=100, null=True)),
                ('sumber_dana', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl', models.DateField(blank=True, null=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.KategoriBelanja')),
                ('tahun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.KategoriTahun')),
            ],
            options={
                'db_table': 'belanja',
            },
        ),
    ]
