# Generated by Django 2.2.17 on 2020-12-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0045_belanja_kategoribelanja_kategoripendapatan_kategoritahun_pendapatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='belanja',
            name='koordinat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='belanja',
            name='progres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
