# Generated by Django 2.2.17 on 2020-12-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0046_auto_20201222_1047'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kepemilikan',
            table='kepemilikan',
        ),
        migrations.AlterModelTable(
            name='pemiliknonwarga',
            table='pemilik_non_warga',
        ),
    ]
