# Generated by Django 2.2.19 on 2021-05-24 06:17

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0046_auto_20210418_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigUmkm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nama_usaha', models.CharField(blank=True, max_length=250, null=True)),
                ('nama_pemilik', models.CharField(blank=True, max_length=250, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=250, null=True)),
                ('geometry', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigumkms', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigumkms', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigumkms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sig_umkm',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SigPajak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('no_kk', models.CharField(blank=True, max_length=250, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=250, null=True)),
                ('biaya_belum_pajak', models.CharField(blank=True, max_length=250, null=True)),
                ('biaya_sudah_pajak', models.CharField(blank=True, max_length=250, null=True)),
                ('geometry', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigpajaks', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigpajaks', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigpajaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sig_pajak',
                'abstract': False,
            },
        ),
    ]
