# Generated by Django 2.2.19 on 2021-05-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0047_sigpajak_sigumkm'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigpajak',
            name='count_belum_pajak',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sigpajak',
            name='count_sudah_pajak',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
