# Generated by Django 2.2.17 on 2020-12-22 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0047_auto_20201222_1349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kepemilikan',
            new_name='KepemilikanWarga',
        ),
        migrations.RemoveField(
            model_name='sigbidang',
            name='pemilik_non_warga',
        ),
        migrations.CreateModel(
            name='KepemilikanNonWarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('namabidang', models.CharField(blank=True, max_length=64, null=True)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigBidang')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_kepemilikannonwargas', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_kepemilikannonwargas', to=settings.AUTH_USER_MODEL)),
                ('non_penduduk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.PemilikNonWarga')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_kepemilikannonwargas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kepemilikan_non_warga',
            },
        ),
        migrations.AddField(
            model_name='sigbidang',
            name='pemiliknonwarga',
            field=models.ManyToManyField(through='v1.KepemilikanNonWarga', to='v1.PemilikNonWarga'),
        ),
    ]
