# Generated by Django 2.2.19 on 2021-05-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0048_auto_20210524_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigpajak',
            name='count',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sigpajak',
            name='total_biaya',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
