# Generated by Django 2.2.17 on 2020-12-22 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0048_auto_20201222_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kepemilikannonwarga',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kepemilikannonwarga',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='kepemilikannonwarga',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='kepemilikannonwarga',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='kepemilikannonwarga',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='kepemilikannonwarga',
            name='updated_by',
        ),
    ]
