# Generated by Django 2.2.19 on 2021-05-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0049_auto_20210524_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sigpajak',
            name='biaya_belum_pajak',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sigpajak',
            name='biaya_sudah_pajak',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sigpajak',
            name='count_belum_pajak',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sigpajak',
            name='count_sudah_pajak',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
