# Generated by Django 2.2.17 on 2020-12-22 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0049_auto_20201222_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemiliknonwarga',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pemiliknonwarga',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pemiliknonwarga',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='pemiliknonwarga',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='pemiliknonwarga',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pemiliknonwarga',
            name='updated_by',
        ),
    ]
