# Generated by Django 2.2.19 on 2021-05-26 04:37

import api_sad_sig.util
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0049_auto_20210526_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='gambar',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination), size=None),
        ),
    ]
