# Generated by Django 2.2.17 on 2020-12-27 09:17

from django.db import migrations, models
import v1.models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0050_auto_20201222_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratKeluar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_surat', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_kirim', models.DateField(blank=True, null=True)),
                ('tgl_surat', models.DateField(blank=True, null=True)),
                ('pengirim', models.CharField(blank=True, max_length=100, null=True)),
                ('kepada', models.CharField(blank=True, max_length=100, null=True)),
                ('perihal', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to=v1.models.file_destination)),
            ],
            options={
                'db_table': 'surat_keluar',
            },
        ),
        migrations.CreateModel(
            name='SuratMasuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_surat', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_terima', models.DateField(blank=True, null=True)),
                ('tgl_surat', models.DateField(blank=True, null=True)),
                ('pengirim', models.CharField(blank=True, max_length=100, null=True)),
                ('kepada', models.CharField(blank=True, max_length=100, null=True)),
                ('perihal', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to=v1.models.file_destination)),
            ],
            options={
                'db_table': 'surat_masuk',
            },
        ),
    ]
