# Generated by Django 2.2.17 on 2020-12-27 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0051_suratkeluar_suratmasuk'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLapor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'StatusLapor',
            },
        ),
        migrations.AddField(
            model_name='lapor',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.StatusLapor'),
        ),
    ]
