# Generated by Django 2.2.19 on 2021-05-26 02:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0051_kategoriproduk_produk_toko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='gambar',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to=''), size=8), size=8),
        ),
    ]
