# Generated by Django 2.2.19 on 2021-05-26 07:20

import api_sad_sig.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0053_auto_20210526_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='batasdesa',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination),
        ),
        migrations.AddField(
            model_name='saddesa',
            name='gambar_sejarah',
            field=models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination),
        ),
        migrations.AddField(
            model_name='saddesa',
            name='gambar_visimisi',
            field=models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination),
        ),
    ]
