# Generated by Django 2.2.17 on 2020-12-29 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0053_auto_20201228_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratkelahiran',
            name='saksi1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='saksi1_surat_lahir', to='v1.Pegawai'),
        ),
        migrations.AlterField(
            model_name='suratkelahiran',
            name='saksi2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='saksi2_surat_lahir', to='v1.Pegawai'),
        ),
    ]
