# Generated by Django 2.2.17 on 2020-12-31 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0054_auto_20201229_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sadkeluarga',
            old_name='alamat',
            new_name='jalan_blok',
        ),
        migrations.RenameField(
            model_name='sadkeluarga',
            old_name='penghasil',
            new_name='penghasilan',
        ),
        migrations.AddField(
            model_name='sadkeluarga',
            name='dusun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadDusun'),
        ),
        migrations.AddField(
            model_name='sadkeluarga',
            name='rw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadRw'),
        ),
        migrations.AlterField(
            model_name='saddesa',
            name='kode_desa',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
