# Generated by Django 2.2.23 on 2021-06-16 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0055_saddesa_gambar_batasdesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisSurat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'jenissurat',
            },
        ),
        migrations.RenameField(
            model_name='sadinventaris',
            old_name='keadaan_akhir',
            new_name='kondisi',
        ),
        migrations.RenameField(
            model_name='sadinventaris',
            old_name='keadaan_awal',
            new_name='lokasi',
        ),
        migrations.RenameField(
            model_name='sadinventaris',
            old_name='tgl_awal',
            new_name='tgl_keluar',
        ),
        migrations.RenameField(
            model_name='sadinventaris',
            old_name='tgl_hapus',
            new_name='tgl_masuk',
        ),
        migrations.RenameField(
            model_name='sadsarpras',
            old_name='keadaan_akhir',
            new_name='kondisi',
        ),
        migrations.RenameField(
            model_name='sadsarpras',
            old_name='keadaan_awal',
            new_name='lokasi',
        ),
        migrations.RenameField(
            model_name='sadsarpras',
            old_name='tgl_awal',
            new_name='tgl_keluar',
        ),
        migrations.RenameField(
            model_name='sadsarpras',
            old_name='tgl_hapus',
            new_name='tgl_masuk',
        ),
        migrations.RemoveField(
            model_name='sadinventaris',
            name='ket_hapus',
        ),
        migrations.RemoveField(
            model_name='sadsarpras',
            name='ket_hapus',
        ),
        migrations.CreateModel(
            name='PersyaratanSurat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persyaratan', models.TextField(blank=True, null=True)),
                ('alur', models.TextField(blank=True, null=True)),
                ('biaya', models.TextField(blank=True, null=True)),
                ('waktu', models.TextField(blank=True, null=True)),
                ('jenis_surat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.JenisSurat')),
            ],
            options={
                'db_table': 'persyaratansurat',
            },
        ),
    ]
