# Generated by Django 2.2.17 on 2021-01-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0055_auto_20201231_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadkelahiran',
            name='waktu_kelahiran',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sadkematian',
            name='tanggal_kematian',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sadlahirmati',
            name='tanggal_lahir',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
