# Generated by Django 2.2.17 on 2021-01-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0056_auto_20210104_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pekerjaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pekerjaan',
            },
        ),
    ]
