# Generated by Django 2.2.23 on 2021-06-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0056_auto_20210616_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='jabatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
