# Generated by Django 2.2.23 on 2021-06-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0057_auto_20210617_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='informasi',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
