# Generated by Django 2.2.17 on 2021-01-05 03:49

from django.db import migrations, models
import v1.models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0058_pendidikan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigbidang',
            name='gambar_atas',
            field=models.ImageField(blank=True, null=True, upload_to=v1.models.file_destination),
        ),
        migrations.AddField(
            model_name='sigbidang',
            name='gambar_depan',
            field=models.ImageField(blank=True, null=True, upload_to=v1.models.file_destination),
        ),
    ]
