# Generated by Django 2.2.17 on 2021-01-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0059_auto_20210105_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'agama',
            },
        ),
        migrations.CreateModel(
            name='Cacat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cacat',
            },
        ),
        migrations.CreateModel(
            name='Goldar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'goldar',
            },
        ),
        migrations.CreateModel(
            name='KelainanFisik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'kelainanfisik',
            },
        ),
        migrations.CreateModel(
            name='Kewarganegaraan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'kewarganegaraan',
            },
        ),
        migrations.CreateModel(
            name='StatusDlmKeluarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'status_dalam_keluarga',
            },
        ),
        migrations.CreateModel(
            name='StatusPerkawinan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'status_perkawinan',
            },
        ),
        migrations.AddField(
            model_name='sadpenduduk',
            name='cacat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sadpenduduk',
            name='kelainan_fisik',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
