# Generated by Django 2.2.17 on 2021-01-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0061_auto_20210106_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='sadrt',
            name='namart',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sadrw',
            name='namarw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
