# Generated by Django 2.2.17 on 2021-01-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0062_auto_20210107_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'asal',
            },
        ),
        migrations.CreateModel(
            name='Golongan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'golongan',
            },
        ),
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'jabatan',
            },
        ),
        migrations.CreateModel(
            name='KeadaanAwal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'keadaan_awal',
            },
        ),
        migrations.CreateModel(
            name='StatusDatangMasuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'status_datang_masuk',
            },
        ),
        migrations.CreateModel(
            name='StatusKesejahteraan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'status_kesejahteraan',
            },
        ),
        migrations.CreateModel(
            name='StatusPns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'status_pns',
            },
        ),
        migrations.CreateModel(
            name='StatusWarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'status_warga',
            },
        ),
    ]
