# Generated by Django 2.2.17 on 2021-01-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0063_asal_golongan_jabatan_keadaanawal_statusdatangmasuk_statuskesejahteraan_statuspns_statuswarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sadkabkota',
            name='nama_kab_kota',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sadpenduduk',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sadprovinsi',
            name='nama_provinsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
