# Generated by Django 2.2.17 on 2021-01-08 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0065_auto_20210107_1341"),
    ]

    database_operations = [
        migrations.AlterModelTable("SuratDomisili", "surat_domisili"),
        migrations.AlterModelTable("SuratSkck", "surat_skck"),
        migrations.AlterModelTable("SuratKelahiran", "surat_kelahiran"),
        migrations.AlterModelTable("SadKelahiran", "sad_kelahiran"),
        migrations.AlterModelTable("SadKematian", "sad_kematian"),
        migrations.AlterModelTable("SadLahirmati", "sad_lahirmati"),
        migrations.AlterModelTable("JenisPindah", "jenis_pindah"),
        migrations.AlterModelTable("AlasanPindah", "alasan_pindah"),
        migrations.AlterModelTable("KlasifikasiPindah", "klasifikasi_pindah"),
        migrations.AlterModelTable("StatusKKTinggal", "status_kk_tinggal"),
        migrations.AlterModelTable("StatusKKPindah", "status_kk_pindah"),
        migrations.AlterModelTable("SadPindahKeluar", "sad_pindah_keluar"),
        migrations.AlterModelTable("SadPindahMasuk", "sad_pindah_masuk"),
    ]

    state_operations = [
        migrations.DeleteModel("SuratDomisili"),
        migrations.DeleteModel("SuratSkck"),
        migrations.DeleteModel("SuratKelahiran"),
        migrations.DeleteModel("SadKelahiran"),
        migrations.DeleteModel("SadKematian"),
        migrations.DeleteModel("SadLahirmati"),
        migrations.DeleteModel("JenisPindah"),
        migrations.DeleteModel("AlasanPindah"),
        migrations.DeleteModel("KlasifikasiPindah"),
        migrations.DeleteModel("StatusKKTinggal"),
        migrations.DeleteModel("StatusKKPindah"),
        migrations.DeleteModel("SadPindahKeluar"),
        migrations.DeleteModel("SadPindahMasuk"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations,
        )
    ]
