# Generated by Django 2.2.17 on 2021-01-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0066_auto_20210109_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisKelahiran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'jenis_kelahiran',
            },
        ),
        migrations.CreateModel(
            name='JenisTempat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'jenis_tempat',
            },
        ),
        migrations.CreateModel(
            name='TenagaKesehatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tenaga_kesehatan',
            },
        ),
    ]
