# Generated by Django 2.2.17 on 2021-01-28 03:03

import api_sad_sig.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0067_jeniskelahiran_jenistempat_tenagakesehatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='belanja',
            name='foto_sebelum',
            field=models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination),
        ),
        migrations.AddField(
            model_name='belanja',
            name='foto_sesudah',
            field=models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination),
        ),
    ]
