# Generated by Django 2.2.17 on 2021-01-29 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0068_auto_20210128_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Belanja',
        ),
    ]
