# Generated by Django 2.2.17 on 2021-01-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0069_auto_20210128_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suratkeluar',
            old_name='arsip',
            new_name='arsip_suratkeluar',
        ),
        migrations.RenameField(
            model_name='suratmasuk',
            old_name='arsip',
            new_name='arsip_suratmasuk',
        ),
    ]
