# Generated by Django 2.2.17 on 2021-01-29 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0070_belanja'),
        ('v1', '0070_auto_20210128_1339'),
    ]

    operations = [
    ]
