# Generated by Django 2.2.17 on 2021-01-29 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0070_belanja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='chip_ektp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sadpenduduk',
            name='alamat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sadpenduduk',
            name='kewarganegaraan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sadpenduduk',
            name='pekerjaan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sadpenduduk',
            name='pendidikan',
            field=models.CharField(blank=True, max_length=100, null=True),
        )
    ]
