# Generated by Django 2.2.17 on 2021-01-29 02:55

import api_sad_sig.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0070_belanja"),
        ("v1", "0070_auto_20210128_1339"),
    ]

    operations = [
        migrations.AddField(
            model_name="belanja",
            name="foto_sebelum",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api_sad_sig.util.file_destination,
            ),
        ),
        migrations.AddField(
            model_name="belanja",
            name="foto_sesudah",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api_sad_sig.util.file_destination,
            ),
        ),
    ]
