# Generated by Django 2.2.17 on 2021-01-29 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0071_merge_20210129_0955"),
    ]

    operations = []
