# Generated by Django 2.2.17 on 2021-01-29 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0072_auto_20210129_0959'),
        ('v1', '0072_auto_20210129_1100'),
    ]

    operations = [
    ]
