# Generated by Django 2.2.17 on 2021-01-29 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0073_merge_20210130_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sadkeluarga',
            name='dusun',
        ),
        migrations.RemoveField(
            model_name='sadkeluarga',
            name='rw',
        ),
        migrations.AlterModelTable(
            name='absensi',
            table='absensi',
        ),
    ]
