# Generated by Django 2.2.17 on 2021-02-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0074_auto_20210130_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='belanja',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
