# Generated by Django 2.2.17 on 2021-02-02 06:11

import api_sad_sig.util
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0075_belanja_deskripsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='KepemilikanNonWarga3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namabidang', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'kepemilikan_non_warga3',
            },
        ),
        migrations.CreateModel(
            name='KepemilikanWarga3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namabidang', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'kepemilikan3',
            },
        ),
        migrations.CreateModel(
            name='PemilikNonWarga3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(blank=True, max_length=32, null=True)),
                ('nama', models.CharField(max_length=64)),
                ('namabidang', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'pemilik_non_warga3',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='pemiliknonwarga',
            name='nik',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='SigPemilik3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('penguasa', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigpemilik3s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigpemilik3s', to=settings.AUTH_USER_MODEL)),
                ('pemilik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadPenduduk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigpemilik3s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sig_pemilik3',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SigBidang3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nbt', models.CharField(blank=True, max_length=20, null=True)),
                ('gambar_atas', models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
                ('gambar_depan', models.ImageField(blank=True, null=True, upload_to=api_sad_sig.util.file_destination)),
                ('penguasa_nonwarga', django.contrib.postgres.fields.jsonb.JSONField(blank=True, max_length=64, null=True)),
                ('geometry', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sigbidang3s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sigbidang3s', to=settings.AUTH_USER_MODEL)),
                ('dusun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigDusun')),
                ('pemiliknonwarga', models.ManyToManyField(through='v1.KepemilikanNonWarga3', to='v1.PemilikNonWarga3')),
                ('pemilikwarga', models.ManyToManyField(through='v1.KepemilikanWarga3', to='v1.SadPenduduk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sigbidang3s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sig_bidang3',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SadKeluarga3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('no_kk', models.CharField(max_length=16, unique=True)),
                ('jalan_blok', models.CharField(blank=True, max_length=100, null=True)),
                ('kode_pos', models.CharField(blank=True, max_length=5, null=True)),
                ('status_kesejahteraan', models.CharField(blank=True, max_length=30, null=True)),
                ('penghasilan', models.IntegerField(blank=True, null=True)),
                ('status_kk', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_sadkeluarga3s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_sadkeluarga3s', to=settings.AUTH_USER_MODEL)),
                ('dusun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadDusun')),
                ('menguasai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dikuasai', to='v1.SigBidang3')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_sadkeluarga3s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sad_keluarga3',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='kepemilikanwarga3',
            name='bidang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigBidang3'),
        ),
        migrations.AddField(
            model_name='kepemilikanwarga3',
            name='penduduk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadPenduduk'),
        ),
        migrations.AddField(
            model_name='kepemilikannonwarga3',
            name='bidang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigBidang3'),
        ),
        migrations.AddField(
            model_name='kepemilikannonwarga3',
            name='non_penduduk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.PemilikNonWarga3'),
        ),
    ]
