# Generated by Django 2.2.17 on 2021-02-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0076_auto_20210202_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuslapor',
            name='warna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
