# Generated by Django 2.2.17 on 2021-02-03 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0078_auto_20210203_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absensi',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='absensi',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='absensi',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='absensi',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='absensi',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='absensi',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='sadkeluarga',
            name='rt',
        ),
        migrations.CreateModel(
            name='Alamat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('alamat', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_alamats', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleted_alamats', to=settings.AUTH_USER_MODEL)),
                ('desa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_alamat', to='v1.SadDesa')),
                ('dusun', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadDusun')),
                ('rt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadRt')),
                ('rw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SadRw')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_alamats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alamat',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sadkeluarga',
            name='alamat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.Alamat'),
        ),
    ]
