# Generated by Django 2.2.17 on 2021-02-04 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0079_auto_20210204_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlasanIzin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'alasan_izin',
            },
        ),
        migrations.RemoveField(
            model_name='absensi',
            name='jumlah',
        ),
        migrations.AlterField(
            model_name='absensi',
            name='alasan_izin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.AlasanIzin'),
        ),
    ]
