# Generated by Django 2.2.17 on 2021-02-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0080_absensi_alasanizin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absensi',
            name='pegawai',
        ),
        migrations.AddField(
            model_name='pegawai',
            name='absensi',
            field=models.ManyToManyField(to='v1.Absensi'),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='jam_keluar',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='jam_masuk',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
