# Generated by Django 2.2.17 on 2021-02-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0080_auto_20210204_1429'),
        ('v1', '0080_absensi_alasanizin'),
    ]

    operations = [
    ]
