# Generated by Django 2.2.17 on 2021-02-05 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0081_auto_20210205_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawai',
            name='absensi',
        ),
        migrations.AddField(
            model_name='absensi',
            name='pegawai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='absensi', to='v1.Pegawai'),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='jam_keluar',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='jam_masuk',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
