# Generated by Django 2.2.17 on 2021-02-06 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0082_auto_20210205_1559'),
        ('v1', '0081_auto_20210205_0807'),
    ]

    operations = [
    ]
