# Generated by Django 2.2.17 on 2021-02-07 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0083_merge_20210206_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigbidang',
            name='sig_dusun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigDusun'),
        ),
        migrations.AddField(
            model_name='sigrw',
            name='sig_dusun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.SigDusun'),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='jam_keluar',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='jam_masuk',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
