# Generated by Django 2.2.17 on 2021-02-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0084_auto_20210207_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cctv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('koordinat', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cctv',
            },
        ),
    ]
