# Generated by Django 2.2.17 on 2021-02-15 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0085_cctv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potensi',
            old_name='alamat',
            new_name='no_telp',
        ),
    ]
