# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - main
    - brangkal
    - gempol
    # - gledeg
    # - jambeyan
    # - jeblok
    # - jungkare
    # - jurangjero
    # - kadirejo
    # - karangan
    # - karanganom
    # - kunden
    # - ngabeyan
    # - padas
    # - pondok
    # - tarubasan
    # - troso
    # - soropaten

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Build
        if: contains(github.ref, 'refs/heads/main')
        run: |
          echo "${{ secrets.DOTENV_MAIN}}" > api_sad_sig/.env
      - name: Build Gempol
        if: contains(github.ref, 'refs/heads/gempol')
        run: |
          echo "${{ secrets.DOTENV_GEMPOL}}" > api_sad_sig/.env
      - name: Build Brangkal
        if: contains(github.ref, 'refs/heads/brangkal')
        run: |
          echo "${{ secrets.DOTENV_BRANGKAL}}" > api_sad_sig/.env
      - name: Deploy 
        run: |
          rsync -av ./ ~/be-app/"$(echo $GITHUB_REF | cut -d'/' -f 3)";
          cd ~/be-app/"$(echo $GITHUB_REF | cut -d'/' -f 3)";
          pipenv install
          pipenv run python manage.py makemigrations --merge
          pipenv run python manage.py migrate
          pipenv run python manage.py collectstatic --noinput
          echo "${{ secrets.PASSWORD }}" | sudo -S supervisorctl restart all