# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - main
    - blanciran
    - brangkal
    - gempol
    - gledeg
    - jambeyan
    - jeblok
    - jungkare
    - jurangjero
    - kadirejo
    - karangan
    - karanganom
    - kunden
    - ngabeyan
    - padas
    - pondok
    - tarubasan
    - troso
    - soropaten

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    env: 
      CI: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Build
        if: contains(github.ref, 'refs/heads/main')
        run: |
          echo "${{ secrets.DOTENV_MAIN}}" > api_sad_sig/.env
      - name: Build Blanciran
        if: contains(github.ref, 'refs/heads/blanciran')
        run: |
          echo "${{ secrets.DOTENV_BRANCILAN}}" > api_sad_sig/.env
      - name: Build Brangkal
        if: contains(github.ref, 'refs/heads/brangkal')
        run: |
          echo "${{ secrets.DOTENV_BRANGKAL}}" > api_sad_sig/.env
      - name: Build Gempol
        if: contains(github.ref, 'refs/heads/gempol')
        run: |
          echo "${{ secrets.DOTENV_GEMPOL}}" > api_sad_sig/.env
      - name: Build Gledeg
        if: contains(github.ref, 'refs/heads/gledeg')
        run: |
          echo "${{ secrets.DOTENV_GLEDEG}}" > api_sad_sig/.env
      - name: Build Jambeyan
        if: contains(github.ref, 'refs/heads/jambeyan')
        run: |
          echo "${{ secrets.DOTENV_JAMBEYAN}}" > api_sad_sig/.env
      - name: Build Jeblok
        if: contains(github.ref, 'refs/heads/jeblok')
        run: |
          echo "${{ secrets.DOTENV_JEBLOK}}" > api_sad_sig/.env
      - name: Build Jungkare
        if: contains(github.ref, 'refs/heads/jungkare')
        run: |
          echo "${{ secrets.DOTENV_JUNGKARE}}" > api_sad_sig/.env
      - name: Build Jurangjero
        if: contains(github.ref, 'refs/heads/jurangjero')
        run: |
          echo "${{ secrets.DOTENV_JURANGJERO}}" > api_sad_sig/.env
      - name: Build Kadirejo
        if: contains(github.ref, 'refs/heads/kadirejo')
        run: |
          echo "${{ secrets.DOTENV_KADIREJO}}" > api_sad_sig/.env
      - name: Build Karangan
        if: contains(github.ref, 'refs/heads/karangan')
        run: |
          echo "${{ secrets.DOTENV_KARANGAN}}" > api_sad_sig/.env
      - name: Build Karanganom
        if: contains(github.ref, 'refs/heads/karanganom')
        run: |
          echo "${{ secrets.DOTENV_KARANGANOM}}" > api_sad_sig/.env
      - name: Build Kunden
        if: contains(github.ref, 'refs/heads/kunden')
        run: |
          echo "${{ secrets.DOTENV_KUNDEN}}" > api_sad_sig/.env
      - name: Build Ngabeyan
        if: contains(github.ref, 'refs/heads/ngabeyan')
        run: |
          echo "${{ secrets.DOTENV_NGABEYAN}}" > api_sad_sig/.env
      - name: Build Padas
        if: contains(github.ref, 'refs/heads/padas')
        run: |
          echo "${{ secrets.DOTENV_PADAS}}" > api_sad_sig/.env
      - name: Build Pondok
        if: contains(github.ref, 'refs/heads/pondok')
        run: |
          echo "${{ secrets.DOTENV_PONDOK}}" > api_sad_sig/.env
      - name: Build Tarubasan
        if: contains(github.ref, 'refs/heads/tarubasan')
        run: |
          echo "${{ secrets.DOTENV_TARUBASAN}}" > api_sad_sig/.env
      - name: Build Troso
        if: contains(github.ref, 'refs/heads/troso')
        run: |
          echo "${{ secrets.DOTENV_TROSO}}" > api_sad_sig/.env
      - name: Build Soropaten
        if: contains(github.ref, 'refs/heads/soropaten')
        run: |
          echo "${{ secrets.DOTENV_SOROPATEN}}" > api_sad_sig/.env
      - name: Deploy 
        run: |
          rsync -avR ./ ~/be-app/"$(echo $GITHUB_REF | cut -d'/' -f 3)";
          cd ~/be-app/"$(echo $GITHUB_REF | cut -d'/' -f 3)";
          pipenv install
          pipenv run python manage.py makemigrations --merge
          pipenv run python manage.py migrate
          pipenv run python manage.py collectstatic --noinput
          echo "${{ secrets.PASSWORD }}" | sudo -S supervisorctl restart all